[tasks.ephemeral]
dependencies = [
	"mkosi-build-image",
]

[tasks.mkosi-build-image]
command = "sudo"
args = [
	"mkosi/builddir/mkosi",
	"-ddebian",
	"-b",
	"--hostname=carbide-preexec",
	"-pcloud-init",
	"--password=password",
	"--format=gpt_squashfs",
	"--split-artifacts",
	"--output-split-root=static/blobs/carbide-ephermeral-image-x86_64.rootfs",
	"--output-split-kernel=static/blobs/carbide-ephemeral-image-x86_64.kernel",
]
dependencies = [
	"mkosi-generate-zipapp",
]

[tasks.mkosi-generate-zipapp]
command = "tools/generate-zipapp.sh"
cwd = "mkosi"

[tasks.ipxe]
dependencies = [
	"ipxe-config",
	"ipxe-install-pcbios-x86_64",
	"ipxe-install-efi-x86_64",
	"ipxe-install-efi-arm64",
]

[tasks.ipxe-config]
script = "cp ipxe/local/*.h ipxe/upstream/src/config/local/"

[tasks.static-output]
command = "mkdir"
args = [ "-p", "static/ipxe" ]

[tasks.ipxe-install-pcbios-x86_64]
command = "mv"
args = ["ipxe/upstream/src/bin-x86_64-pcbios/ipxe.kpxe", "static/ipxe"]
dependencies = [
	"ipxe-build-pcbios-x86_64",
	"static-output"
]

[tasks.ipxe-install-efi-x86_64]
command = "mv"
args = ["ipxe/upstream/src/bin-x86_64-efi/ipxe.efi", "static/ipxe"]
dependencies = [
	"ipxe-build-efi-x86_64",
	"static-output"
]

[tasks.ipxe-install-efi-arm64]
command = "mv"
args = ["ipxe/upstream/src/bin-arm64-efi/ipxe.efi", "static/ipxe"]
dependencies = [
	"ipxe-build-efi-arm64",
	"static-output"
]

[tasks.ipxe-build-pcbios-x86_64]
command = "make"
args = [ "bin-x86_64-pcbios/ipxe.kpxe", "EMBED=../../local/embed.ipxe" ]
cwd = "ipxe/upstream/src"

[tasks.ipxe-build-efi-x86_64]
command = "make"
args = [ "bin-x86_64-efi/ipxe.efi", "EMBED=../../local/embed.ipxe"]
cwd = "ipxe/upstream/src"

[tasks.ipxe-build-efi-arm64]
env = { "CROSS_COMPILE" = "aarch64-linux-gnu-", "ARCH" = "arm64", CC="aarch64-linux-gnu-gcc-11" }
command = "make"
args = [ "bin-arm64-efi/ipxe.efi", "EMBED=../../local/embed.ipxe"]
cwd = "ipxe/upstream/src"
