[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.book]
workspace = false
command = "find"
args = ["public"]
dependencies = [
	"book-compile",
]

[tasks.runtime-container]
workspace = false
command = "docker"
args = ["build", "-t", "carbide-runtime:latest", "."]
env = { "DOCKER_BUILDKIT" = "1" }

[tasks.book-compile]
workspace = false
command = "mdbook"
args = ["build", "-d", "../public", "book"]

[tasks.attribution]
workspace = false
command = "cargo"
args = ["license", "--avoid-build-deps", "--avoid-dev-deps", "--json"]
