sequenceDiagram
  participant Machine
  participant DHCP Service
  participant PXE Service
  participant Metal API
  participant PostgreSQL

  Machine->>DHCP Service: DHCP REQUEST
  DHCP Service->>Metal API: Request Machine info

  Metal API->>Metal API: Generate hostname
  Metal API->>PostgreSQL: Get next IP for network
  PostgreSQL-->>Metal API: Next IP
  Metal API->>Metal API: Assign IP to host
  Metal API->>PostgreSQL: Insert machine to database

  loop State Machine
    PostgreSQL->>PostgreSQL: Start state machine (start "new")
  end

  PostgreSQL-->>Metal API: Basic machine object
  Metal API-->>DHCP Service: Basic machine object
  DHCP Service-->>Machine: DHCP REPLY
  
  Machine-->>PXE Service: Download iPXE kernel (tftp/http)
  PXE Service-->>Machine: iPXE kernel

  Machine->>PXE Service: Get boot config
  PXE Service->>Metal API: Get machine state
  Metal API-->>PXE Service: state = new
  PXE Service-->>Machine: Boot OS inventory image
