/*
 * SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 *
 * NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 * property and proprietary rights in and to this material, related
 * documentation and any modifications thereto. Any use, reproduction,
 * disclosure or distribution of this material and related documentation
 * without an express license agreement from NVIDIA CORPORATION or
 * its affiliates is strictly prohibited.
 */
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    let autogenerated_rust_output_directory = PathBuf::from("src/protos");
    // The reflection path is part of the output directory (which might be debug or release),
    // so that different builds get a different binary file and concurrent builds don't collide
    let reflection = out_dir.join("forge.bin");

    tonic_build::configure()
        .file_descriptor_set_path(reflection)
        .extern_path(".google.protobuf.Duration", "crate::Duration")
        .extern_path(".google.protobuf.Timestamp", "crate::Timestamp")
        .include_file("prost_common.rs")
        .type_attribute(".health", "#[derive(serde::Serialize)]")
        .type_attribute(
            ".machine_discovery",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            ".site_explorer",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.AdminForceDeleteMachineRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.AdminForceDeleteMachineResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.CredentialResponse", "#[derive(serde::Serialize)]")
        .type_attribute("forge.Domain", "#[derive(serde::Serialize)]")
        .type_attribute("forge.DomainList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.FlatInterfaceConfig", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InstanceInterfaceConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.InstanceInterfaceConfig.network_details",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.InstanceIBInterfaceConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.InstanceUpdateStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceNetworkConfig", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InstanceInfinibandConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.InstanceStorageConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceConfig", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InstanceInterfaceStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.InstanceIBInterfaceStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.InstanceNetworkStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InstanceInfinibandStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.InstanceStorageStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceTenantStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.Instance", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.Metadata",
            "#[derive(serde::Serialize, serde::Deserialize, Eq)]",
        )
        .type_attribute(
            "forge.Label",
            "#[derive(serde::Serialize, serde::Deserialize, Eq)]",
        )
        .type_attribute(
            "forge.InstancePhoneHomeLastContactRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.InstancePhoneHomeLastContactResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.InstanceList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.Machine", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.MachineCapabilitiesSet",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesCpu",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesGpu",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesMemory",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesStorage",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesNetwork",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesInfiniband",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesDpu",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.MachineList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineEvent", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineInterface", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InfinibandStatusObservation",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.MachineIbInterface", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineState", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineArchitecture", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineInventory", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.MachineInventorySoftwareComponent",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.HealthOverrideOrigin", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.ManagedHostNetworkConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.ManagedHostNetworkConfigResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.NetworkPrefix", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NetworkPrefixEvent", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NetworkSegment", "#[derive(serde::Serialize)]")
        .type_attribute("forge.IBPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.IBPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.IBPartition", "#[derive(serde::Serialize)]")
        .type_attribute("forge.IBPartitionList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.IpxeOperatingSystem", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NetworkSegmentList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.OperatingSystem", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.OperatingSystem.variant",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.InterfaceList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.NetworkSegmentStateHistory",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.Tenant", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantContent", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantKeyset", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantKeysetContent", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantKeysetList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.TenantKeysetIdentifier",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.TenantPublicKey", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantKeySetList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.VpcResourceState", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineBootOverride", "#[derive(serde::Serialize)]")
        .type_attribute("forge.ConnectedDevice", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NetworkDevice", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NetworkTopologyData", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InstanceInterfaceStatusObservation",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.FabricInterfaceData", "#[derive(serde::Serialize)]")
        .type_attribute("forge.LinkData", "#[derive(serde::Serialize)]")
        .type_attribute("forge.DpuNetworkStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.LastDhcpRequest", "#[derive(serde::Serialize)]")
        .type_attribute("forge.ResourcePool", "#[derive(serde::Serialize)]")
        .type_attribute("forge.Vpc", "#[derive(serde::Serialize)]")
        .type_attribute("forge.VpcList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.StorageClusterAttributes",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.VpcPrefix", "#[derive(serde::Serialize)]")
        .type_attribute("forge.StorageCluster", "#[derive(serde::Serialize)]")
        .type_attribute("forge.StoragePoolAttributes", "#[derive(serde::Serialize)]")
        .type_attribute("forge.StoragePool", "#[derive(serde::Serialize)]")
        .type_attribute("forge.StorageVolumeStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.StorageVolumeAttributes",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.StorageVolume", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.DeleteStoragePoolRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.ListStoragePoolRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.ListStoragePoolResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.DeleteStorageVolumeRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.ListStorageVolumeRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.ListStorageVolumeResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.OsImageAttributes", "#[derive(serde::Serialize)]")
        .type_attribute("forge.OsImage", "#[derive(serde::Serialize)]")
        .type_attribute("forge.ListOsImageRequest", "#[derive(serde::Serialize)]")
        .type_attribute("forge.ListOsImageResponse", "#[derive(serde::Serialize)]")
        .type_attribute("DeleteOsImageRequest", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.MachineDiscoveryInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "common.UUID",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineDiscoveryInfo.discovery_data",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.DhcpDiscovery",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.UserRoles",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.BMCRequestType",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "forge.BmcInfo",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "forge.bmc_meta_data_update_request.DataItem",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "DataItem",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "bmc_meta_data_update_request",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "BMCMetaDataUpdateRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "ControllerStateReason",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "RuntimeConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("StateSla", "#[derive(serde::Serialize)]")
        .type_attribute(
            "BuildInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("MachineValidationResultList", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationResult", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationRunList", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationRun", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedMachine", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedMachineList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "TpmCaCertDetail",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmCaCertDetailCollection",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmEkCertStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmEkCertStatusCollection",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmCaAddedCaStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmCaCertId",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("MachineValidationState", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationCompleted", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationInProgress", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationStarted", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "MachineValidationExternalConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestUpdateRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestAddRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestsGetRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestUpdateRequest.Payload",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.RedfishBrowseResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.InstanceNetworkRestrictions",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .build_server(true)
        .build_client(true)
        .protoc_arg("--experimental_allow_proto3_optional")
        .out_dir(autogenerated_rust_output_directory)
        .compile_protos(
            &[
                "proto/common.proto",
                "proto/forge.proto",
                "proto/machine_discovery.proto",
                "proto/site_explorer.proto",
            ],
            &["proto"],
        )
        .unwrap();

    Ok(())
}
