/*
 * SPDX-FileCopyrightText: Copyright (c) 2021-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 *
 * NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 * property and proprietary rights in and to this material, related
 * documentation and any modifications thereto. Any use, reproduction,
 * disclosure or distribution of this material and related documentation
 * without an express license agreement from NVIDIA CORPORATION or
 * its affiliates is strictly prohibited.
 */
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let autogenerated_rust_output_directory = PathBuf::from("src/protos");
    let reflection = autogenerated_rust_output_directory.join("forge.bin");

    tonic_build::configure()
        .file_descriptor_set_path(&reflection)
        .include_file("common.rs")
        .type_attribute("forge.MachineState", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineInterface", "#[derive(serde::Serialize)]")
        .type_attribute("forge.UUID", "#[derive(serde::Serialize)]")
        .type_attribute(".machine_discovery", "#[derive(serde::Deserialize)]")
        .type_attribute(
            "forge.InstanceInterfaceConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.InstanceNetworkConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceConfig", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InstanceInterfaceStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.InstanceNetworkStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceTenantStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.Instance", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceList", "#[derive(serde::Serialize)]")
        .build_server(true)
        .build_client(true)
        .protoc_arg("--experimental_allow_proto3_optional")
        .out_dir(autogenerated_rust_output_directory)
        .compile(
            &[
                "proto/forge.proto",
                "proto/machine_discovery.proto",
                "proto/security_group.proto",
            ],
            &["proto"],
        )
        .unwrap();

    Ok(())
}
