// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ResourceGroupClient is the client API for ResourceGroup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceGroupClient interface {
	// Creates a resource group.
	CreateResourceGroup(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ServiceStatus, error)
	// Completely update ResourceGroup, used to add/remove ManagedResource in the ResourceGroup.
	UpdateResourceGroup(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ServiceStatus, error)
	// ListResourceGroup get one or all ResourceGroups.
	ListResourceGroup(ctx context.Context, in *ResourceGroupName, opts ...grpc.CallOption) (ResourceGroup_ListResourceGroupClient, error)
	// Delete ResourceGroup.
	DeleteResourceGroup(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ServiceStatus, error)
	// Update a ManagedResource. The ResourceGroup it belongs must already exist.
	UpdateManagedResource(ctx context.Context, in *ManagedResourceSpec, opts ...grpc.CallOption) (*ServiceStatus, error)
	// Retrieve ManagedResource status from a ResourceGroup. It also returns IP addresses
	// to access the hosts if applicable.
	ListManagedResource(ctx context.Context, in *ResourceGroupName, opts ...grpc.CallOption) (ResourceGroup_ListManagedResourceClient, error)
}

type resourceGroupClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceGroupClient(cc grpc.ClientConnInterface) ResourceGroupClient {
	return &resourceGroupClient{cc}
}

func (c *resourceGroupClient) CreateResourceGroup(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ServiceStatus, error) {
	out := new(ServiceStatus)
	err := c.cc.Invoke(ctx, "/rpc.ResourceGroup/CreateResourceGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceGroupClient) UpdateResourceGroup(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ServiceStatus, error) {
	out := new(ServiceStatus)
	err := c.cc.Invoke(ctx, "/rpc.ResourceGroup/UpdateResourceGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceGroupClient) ListResourceGroup(ctx context.Context, in *ResourceGroupName, opts ...grpc.CallOption) (ResourceGroup_ListResourceGroupClient, error) {
	stream, err := c.cc.NewStream(ctx, &ResourceGroup_ServiceDesc.Streams[0], "/rpc.ResourceGroup/ListResourceGroup", opts...)
	if err != nil {
		return nil, err
	}
	x := &resourceGroupListResourceGroupClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ResourceGroup_ListResourceGroupClient interface {
	Recv() (*ResourceGroupStatus, error)
	grpc.ClientStream
}

type resourceGroupListResourceGroupClient struct {
	grpc.ClientStream
}

func (x *resourceGroupListResourceGroupClient) Recv() (*ResourceGroupStatus, error) {
	m := new(ResourceGroupStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *resourceGroupClient) DeleteResourceGroup(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ServiceStatus, error) {
	out := new(ServiceStatus)
	err := c.cc.Invoke(ctx, "/rpc.ResourceGroup/DeleteResourceGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceGroupClient) UpdateManagedResource(ctx context.Context, in *ManagedResourceSpec, opts ...grpc.CallOption) (*ServiceStatus, error) {
	out := new(ServiceStatus)
	err := c.cc.Invoke(ctx, "/rpc.ResourceGroup/UpdateManagedResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceGroupClient) ListManagedResource(ctx context.Context, in *ResourceGroupName, opts ...grpc.CallOption) (ResourceGroup_ListManagedResourceClient, error) {
	stream, err := c.cc.NewStream(ctx, &ResourceGroup_ServiceDesc.Streams[1], "/rpc.ResourceGroup/ListManagedResource", opts...)
	if err != nil {
		return nil, err
	}
	x := &resourceGroupListManagedResourceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ResourceGroup_ListManagedResourceClient interface {
	Recv() (*ManagedResourceStatus, error)
	grpc.ClientStream
}

type resourceGroupListManagedResourceClient struct {
	grpc.ClientStream
}

func (x *resourceGroupListManagedResourceClient) Recv() (*ManagedResourceStatus, error) {
	m := new(ManagedResourceStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ResourceGroupServer is the server API for ResourceGroup service.
// All implementations must embed UnimplementedResourceGroupServer
// for forward compatibility
type ResourceGroupServer interface {
	// Creates a resource group.
	CreateResourceGroup(context.Context, *ResourceGroupSpec) (*ServiceStatus, error)
	// Completely update ResourceGroup, used to add/remove ManagedResource in the ResourceGroup.
	UpdateResourceGroup(context.Context, *ResourceGroupSpec) (*ServiceStatus, error)
	// ListResourceGroup get one or all ResourceGroups.
	ListResourceGroup(*ResourceGroupName, ResourceGroup_ListResourceGroupServer) error
	// Delete ResourceGroup.
	DeleteResourceGroup(context.Context, *ResourceGroupSpec) (*ServiceStatus, error)
	// Update a ManagedResource. The ResourceGroup it belongs must already exist.
	UpdateManagedResource(context.Context, *ManagedResourceSpec) (*ServiceStatus, error)
	// Retrieve ManagedResource status from a ResourceGroup. It also returns IP addresses
	// to access the hosts if applicable.
	ListManagedResource(*ResourceGroupName, ResourceGroup_ListManagedResourceServer) error
	mustEmbedUnimplementedResourceGroupServer()
}

// UnimplementedResourceGroupServer must be embedded to have forward compatible implementations.
type UnimplementedResourceGroupServer struct {
}

func (UnimplementedResourceGroupServer) CreateResourceGroup(context.Context, *ResourceGroupSpec) (*ServiceStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResourceGroup not implemented")
}
func (UnimplementedResourceGroupServer) UpdateResourceGroup(context.Context, *ResourceGroupSpec) (*ServiceStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateResourceGroup not implemented")
}
func (UnimplementedResourceGroupServer) ListResourceGroup(*ResourceGroupName, ResourceGroup_ListResourceGroupServer) error {
	return status.Errorf(codes.Unimplemented, "method ListResourceGroup not implemented")
}
func (UnimplementedResourceGroupServer) DeleteResourceGroup(context.Context, *ResourceGroupSpec) (*ServiceStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResourceGroup not implemented")
}
func (UnimplementedResourceGroupServer) UpdateManagedResource(context.Context, *ManagedResourceSpec) (*ServiceStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateManagedResource not implemented")
}
func (UnimplementedResourceGroupServer) ListManagedResource(*ResourceGroupName, ResourceGroup_ListManagedResourceServer) error {
	return status.Errorf(codes.Unimplemented, "method ListManagedResource not implemented")
}
func (UnimplementedResourceGroupServer) mustEmbedUnimplementedResourceGroupServer() {}

// UnsafeResourceGroupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceGroupServer will
// result in compilation errors.
type UnsafeResourceGroupServer interface {
	mustEmbedUnimplementedResourceGroupServer()
}

func RegisterResourceGroupServer(s grpc.ServiceRegistrar, srv ResourceGroupServer) {
	s.RegisterService(&ResourceGroup_ServiceDesc, srv)
}

func _ResourceGroup_CreateResourceGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupServer).CreateResourceGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ResourceGroup/CreateResourceGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupServer).CreateResourceGroup(ctx, req.(*ResourceGroupSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceGroup_UpdateResourceGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupServer).UpdateResourceGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ResourceGroup/UpdateResourceGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupServer).UpdateResourceGroup(ctx, req.(*ResourceGroupSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceGroup_ListResourceGroup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResourceGroupName)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceGroupServer).ListResourceGroup(m, &resourceGroupListResourceGroupServer{stream})
}

type ResourceGroup_ListResourceGroupServer interface {
	Send(*ResourceGroupStatus) error
	grpc.ServerStream
}

type resourceGroupListResourceGroupServer struct {
	grpc.ServerStream
}

func (x *resourceGroupListResourceGroupServer) Send(m *ResourceGroupStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _ResourceGroup_DeleteResourceGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupServer).DeleteResourceGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ResourceGroup/DeleteResourceGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupServer).DeleteResourceGroup(ctx, req.(*ResourceGroupSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceGroup_UpdateManagedResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagedResourceSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceGroupServer).UpdateManagedResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ResourceGroup/UpdateManagedResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceGroupServer).UpdateManagedResource(ctx, req.(*ManagedResourceSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceGroup_ListManagedResource_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResourceGroupName)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceGroupServer).ListManagedResource(m, &resourceGroupListManagedResourceServer{stream})
}

type ResourceGroup_ListManagedResourceServer interface {
	Send(*ManagedResourceStatus) error
	grpc.ServerStream
}

type resourceGroupListManagedResourceServer struct {
	grpc.ServerStream
}

func (x *resourceGroupListManagedResourceServer) Send(m *ManagedResourceStatus) error {
	return x.ServerStream.SendMsg(m)
}

// ResourceGroup_ServiceDesc is the grpc.ServiceDesc for ResourceGroup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceGroup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.ResourceGroup",
	HandlerType: (*ResourceGroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateResourceGroup",
			Handler:    _ResourceGroup_CreateResourceGroup_Handler,
		},
		{
			MethodName: "UpdateResourceGroup",
			Handler:    _ResourceGroup_UpdateResourceGroup_Handler,
		},
		{
			MethodName: "DeleteResourceGroup",
			Handler:    _ResourceGroup_DeleteResourceGroup_Handler,
		},
		{
			MethodName: "UpdateManagedResource",
			Handler:    _ResourceGroup_UpdateManagedResource_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListResourceGroup",
			Handler:       _ResourceGroup_ListResourceGroup_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListManagedResource",
			Handler:       _ResourceGroup_ListManagedResource_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc/rpc.proto",
}

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Probe agent aliveness.
	AliveProbe(ctx context.Context, in *Probe, opts ...grpc.CallOption) (*AgentStatus, error)
	// Start or stop ovn controller on DPU.
	SetOvn(ctx context.Context, in *OVNConfig, opts ...grpc.CallOption) (*ServiceStatus, error)
	// Add or remove dhcp relay agent on DPU.
	SetDHCPRelay(ctx context.Context, in *DHCPRelay, opts ...grpc.CallOption) (*ServiceStatus, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) AliveProbe(ctx context.Context, in *Probe, opts ...grpc.CallOption) (*AgentStatus, error) {
	out := new(AgentStatus)
	err := c.cc.Invoke(ctx, "/rpc.AgentService/AliveProbe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SetOvn(ctx context.Context, in *OVNConfig, opts ...grpc.CallOption) (*ServiceStatus, error) {
	out := new(ServiceStatus)
	err := c.cc.Invoke(ctx, "/rpc.AgentService/SetOvn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SetDHCPRelay(ctx context.Context, in *DHCPRelay, opts ...grpc.CallOption) (*ServiceStatus, error) {
	out := new(ServiceStatus)
	err := c.cc.Invoke(ctx, "/rpc.AgentService/SetDHCPRelay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	// Probe agent aliveness.
	AliveProbe(context.Context, *Probe) (*AgentStatus, error)
	// Start or stop ovn controller on DPU.
	SetOvn(context.Context, *OVNConfig) (*ServiceStatus, error)
	// Add or remove dhcp relay agent on DPU.
	SetDHCPRelay(context.Context, *DHCPRelay) (*ServiceStatus, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) AliveProbe(context.Context, *Probe) (*AgentStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AliveProbe not implemented")
}
func (UnimplementedAgentServiceServer) SetOvn(context.Context, *OVNConfig) (*ServiceStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetOvn not implemented")
}
func (UnimplementedAgentServiceServer) SetDHCPRelay(context.Context, *DHCPRelay) (*ServiceStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDHCPRelay not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_AliveProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Probe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AliveProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.AgentService/AliveProbe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AliveProbe(ctx, req.(*Probe))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SetOvn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OVNConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SetOvn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.AgentService/SetOvn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SetOvn(ctx, req.(*OVNConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SetDHCPRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DHCPRelay)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SetDHCPRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.AgentService/SetDHCPRelay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SetDHCPRelay(ctx, req.(*DHCPRelay))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AliveProbe",
			Handler:    _AgentService_AliveProbe_Handler,
		},
		{
			MethodName: "SetOvn",
			Handler:    _AgentService_SetOvn_Handler,
		},
		{
			MethodName: "SetDHCPRelay",
			Handler:    _AgentService_SetDHCPRelay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/rpc.proto",
}
