sequenceDiagram
  participant Machine
  participant DHCP Service
  participant PXE Service
  participant Metal API
  participant PostgreSQL

  Machine->>DHCP Service: DHCP REQUEST
  DHCP Service->>Metal API: Request Machine info
  Metal API->>PostgreSQL: Request Machine info

  PostgreSQL-->>Metal API: Complete machine object
  Metal API-->>DHCP Service: Machine object
  DHCP Service-->>Machine: DHCP REPLY
  
  Machine-->>PXE Service: Download iPXE kernel (tftp/http)
  PXE Service-->>Machine: iPXE kernel

  Machine->>PXE Service: Get boot template
  PXE Service->>Metal API: Get machine state
  Metal API-->>PXE Service: state = inventoried
  PXE Service-->>Machine: Boot OS burn-in image
