# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vagrant.plugins = %w[vagrant-env vagrant-cloudinit]

#  config.vm.box_check_update = false
  config.env.enable

  config.vm.define :relay do |relay|
    relay.vm.box = "ubuntu/impish64"
    relay.vm.hostname = "relay"

    relay.vm.network :public_network, bridge: "enp47s0f0"
    relay.vm.network :private_network, ip: "192.168.0.1", virtualbox__intnet: true

    relay.vm.cloud_init :user_data, content_type: "text/cloud-config", path: "relay.yml"

    relay.vm.provider :virtualbox do |vb, config|
      vb.customize ['modifyvm', :id, '--boot1', 'disk']
    end
  end

# TODO: empty booting client
  config.vm.define :client, autostart: false do |client|
    client.vm.box = 'sridhav/empty'
    client.vm.box_version = "1.0"
    client.vm.hostname = "pxe-client"

    client.vm.network :private_network, type: 'dhcp', virtualbox__intnet: true

    client.vm.provider :virtualbox do |vb, config|
      # make sure this vm has enough memory to load the root fs into memory.
      vb.memory = 4096

      # let vagrant known that the guest does not have the guest additions nor a functional vboxsf or shared folders.
      vb.check_guest_additions = false
      vb.functional_vboxsf = false
      config.vm.synced_folder '.', '/vagrant', disabled: true

      # configure for PXE boot.
      vb.customize ['modifyvm', :id, '--firmware', 'efi']
      vb.customize ["modifyvm", :id, "--nic1", "none"]
      vb.customize ['modifyvm', :id, '--boot1', 'net']
      vb.customize ['modifyvm', :id, '--nicbootprio1', '1']
    end
  end
end
