# syntax=docker/dockerfile:1.7

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM nico-devspace-core-artifacts AS artifacts

FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p \
  /opt/carbide/pxe/templates \
  /opt/carbide/scout-firmware-scripts \
  /forge-boot-artifacts/blobs

COPY --from=artifacts /artifacts/carbide /opt/carbide/carbide
COPY pxe/templates/ /opt/carbide/pxe/templates/
COPY pxe/scout-firmware-scripts/ /opt/carbide/scout-firmware-scripts/
