#!/bin/bash

ADDRESS=$(ip -json addr show oob_net0  | jq -r '.[].addr_info[] | select(.family == "inet").local')

DATA= cat<< EOF > /etc/otelcol-contrib/fd_configs/fd_discovery.yaml
- targets: [ "127.0.0.1:8888" ]
  labels:
    ipaddress: $ADDRESS
    component: "fmds"
- targets: [ "127.0.0.1:9100" ]
  labels:
    ipaddress: $ADDRESS
    component: "dts"
EOF
