# SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[env]
# e.g. 2023.09-72-g1641d986
DPU_AGENT_PKG_VERSION = { script = ["echo $(git describe --tags --first-parent --always --long | cut -c 2-)"] }

[tasks.build-forge-scout]
category = "Build"
description = "cross compile forge-scout locally"
workspace = false
script = '''
docker run --rm -v $REPO_ROOT:/carbide --user $(id -u):$(id -g) \
    --env CARGO_HOME=/cargo \
    -v $CARGO_HOME:/cargo \
    build-artifacts-container-cross-aarch64 \
    "cargo" \
    "build" \
    "--release" \
    "--target=aarch64-unknown-linux-gnu" \
    "--bin" \
    "forge-scout" 
docker run --rm -v $REPO_ROOT:/carbide --user $(id -u):$(id -g) build-artifacts-container-cross-aarch64 "aarch64-linux-gnu-strip" \
    "/carbide/target/aarch64-unknown-linux-gnu/release/forge-scout"   
'''
dependencies = [
    { name = "build-cross-docker-image", path = "${REPO_ROOT}" },
]

