// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: common_nico.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemPowerControl int32

const (
	SystemPowerControl_SYSTEM_POWER_CONTROL_UNKNOWN SystemPowerControl = 0
	// Power on a machine
	SystemPowerControl_SYSTEM_POWER_CONTROL_ON SystemPowerControl = 1
	// Graceful host shutdown
	SystemPowerControl_SYSTEM_POWER_CONTROL_GRACEFUL_SHUTDOWN SystemPowerControl = 2
	// Forcefully powers a machine off
	SystemPowerControl_SYSTEM_POWER_CONTROL_FORCE_OFF SystemPowerControl = 3
	// Graceful restart. Asks the OS to restart via ACPI
	SystemPowerControl_SYSTEM_POWER_CONTROL_GRACEFUL_RESTART SystemPowerControl = 4
	// Force restart. This is equivalent to pressing the reset button on the front panel.
	SystemPowerControl_SYSTEM_POWER_CONTROL_FORCE_RESTART SystemPowerControl = 5
	// AC powercycle. This is equivalent to unplugging and reconnecting power cables. Not supported on Vikings.
	SystemPowerControl_SYSTEM_POWER_CONTROL_AC_POWERCYCLE SystemPowerControl = 6
)

// Enum value maps for SystemPowerControl.
var (
	SystemPowerControl_name = map[int32]string{
		0: "SYSTEM_POWER_CONTROL_UNKNOWN",
		1: "SYSTEM_POWER_CONTROL_ON",
		2: "SYSTEM_POWER_CONTROL_GRACEFUL_SHUTDOWN",
		3: "SYSTEM_POWER_CONTROL_FORCE_OFF",
		4: "SYSTEM_POWER_CONTROL_GRACEFUL_RESTART",
		5: "SYSTEM_POWER_CONTROL_FORCE_RESTART",
		6: "SYSTEM_POWER_CONTROL_AC_POWERCYCLE",
	}
	SystemPowerControl_value = map[string]int32{
		"SYSTEM_POWER_CONTROL_UNKNOWN":           0,
		"SYSTEM_POWER_CONTROL_ON":                1,
		"SYSTEM_POWER_CONTROL_GRACEFUL_SHUTDOWN": 2,
		"SYSTEM_POWER_CONTROL_FORCE_OFF":         3,
		"SYSTEM_POWER_CONTROL_GRACEFUL_RESTART":  4,
		"SYSTEM_POWER_CONTROL_FORCE_RESTART":     5,
		"SYSTEM_POWER_CONTROL_AC_POWERCYCLE":     6,
	}
)

func (x SystemPowerControl) Enum() *SystemPowerControl {
	p := new(SystemPowerControl)
	*p = x
	return p
}

func (x SystemPowerControl) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemPowerControl) Descriptor() protoreflect.EnumDescriptor {
	return file_common_nico_proto_enumTypes[0].Descriptor()
}

func (SystemPowerControl) Type() protoreflect.EnumType {
	return &file_common_nico_proto_enumTypes[0]
}

func (x SystemPowerControl) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemPowerControl.Descriptor instead.
func (SystemPowerControl) EnumDescriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{0}
}

type MachineId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineId) Reset() {
	*x = MachineId{}
	mi := &file_common_nico_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineId) ProtoMessage() {}

func (x *MachineId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineId.ProtoReflect.Descriptor instead.
func (*MachineId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{0}
}

func (x *MachineId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MachineIdList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineIds    []*MachineId           `protobuf:"bytes,1,rep,name=machine_ids,json=machineIds,proto3" json:"machine_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineIdList) Reset() {
	*x = MachineIdList{}
	mi := &file_common_nico_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineIdList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineIdList) ProtoMessage() {}

func (x *MachineIdList) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineIdList.ProtoReflect.Descriptor instead.
func (*MachineIdList) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{1}
}

func (x *MachineIdList) GetMachineIds() []*MachineId {
	if x != nil {
		return x.MachineIds
	}
	return nil
}

// A list of strings
// This is different than "repeated string" since using StringList
// allows to express a nullable/optional list
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_common_nico_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{2}
}

func (x *StringList) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_common_nico_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{3}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PowerShelfId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerShelfId) Reset() {
	*x = PowerShelfId{}
	mi := &file_common_nico_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerShelfId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerShelfId) ProtoMessage() {}

func (x *PowerShelfId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerShelfId.ProtoReflect.Descriptor instead.
func (*PowerShelfId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{4}
}

func (x *PowerShelfId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RackId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RackId) Reset() {
	*x = RackId{}
	mi := &file_common_nico_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RackId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RackId) ProtoMessage() {}

func (x *RackId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RackId.ProtoReflect.Descriptor instead.
func (*RackId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{5}
}

func (x *RackId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RackProfileId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RackProfileId) Reset() {
	*x = RackProfileId{}
	mi := &file_common_nico_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RackProfileId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RackProfileId) ProtoMessage() {}

func (x *RackProfileId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RackProfileId.ProtoReflect.Descriptor instead.
func (*RackProfileId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{6}
}

func (x *RackProfileId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SwitchId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchId) Reset() {
	*x = SwitchId{}
	mi := &file_common_nico_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchId) ProtoMessage() {}

func (x *SwitchId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchId.ProtoReflect.Descriptor instead.
func (*SwitchId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{7}
}

func (x *SwitchId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Uint32List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []uint32               `protobuf:"varint,1,rep,packed,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uint32List) Reset() {
	*x = Uint32List{}
	mi := &file_common_nico_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint32List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint32List) ProtoMessage() {}

func (x *Uint32List) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint32List.ProtoReflect.Descriptor instead.
func (*Uint32List) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{8}
}

func (x *Uint32List) GetItems() []uint32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type RouteTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Vni           uint32                 `protobuf:"varint,2,opt,name=vni,proto3" json:"vni,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTarget) Reset() {
	*x = RouteTarget{}
	mi := &file_common_nico_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTarget) ProtoMessage() {}

func (x *RouteTarget) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTarget.ProtoReflect.Descriptor instead.
func (*RouteTarget) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{9}
}

func (x *RouteTarget) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *RouteTarget) GetVni() uint32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

// Placeholder ID types: These are not code-generated, but overridden by our own type-safe UUID wrappers. They are
// identical to common.UUID over the wire, for backwards compatibility.
type DomainId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainId) Reset() {
	*x = DomainId{}
	mi := &file_common_nico_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainId) ProtoMessage() {}

func (x *DomainId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainId.ProtoReflect.Descriptor instead.
func (*DomainId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{10}
}

func (x *DomainId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MachineInterfaceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineInterfaceId) Reset() {
	*x = MachineInterfaceId{}
	mi := &file_common_nico_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineInterfaceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInterfaceId) ProtoMessage() {}

func (x *MachineInterfaceId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInterfaceId.ProtoReflect.Descriptor instead.
func (*MachineInterfaceId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{11}
}

func (x *MachineInterfaceId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type VpcId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpcId) Reset() {
	*x = VpcId{}
	mi := &file_common_nico_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpcId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpcId) ProtoMessage() {}

func (x *VpcId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpcId.ProtoReflect.Descriptor instead.
func (*VpcId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{12}
}

func (x *VpcId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type VpcPrefixId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpcPrefixId) Reset() {
	*x = VpcPrefixId{}
	mi := &file_common_nico_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpcPrefixId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpcPrefixId) ProtoMessage() {}

func (x *VpcPrefixId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpcPrefixId.ProtoReflect.Descriptor instead.
func (*VpcPrefixId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{13}
}

func (x *VpcPrefixId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type VpcPeeringId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpcPeeringId) Reset() {
	*x = VpcPeeringId{}
	mi := &file_common_nico_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpcPeeringId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpcPeeringId) ProtoMessage() {}

func (x *VpcPeeringId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpcPeeringId.ProtoReflect.Descriptor instead.
func (*VpcPeeringId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{14}
}

func (x *VpcPeeringId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type IBPartitionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IBPartitionId) Reset() {
	*x = IBPartitionId{}
	mi := &file_common_nico_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IBPartitionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IBPartitionId) ProtoMessage() {}

func (x *IBPartitionId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IBPartitionId.ProtoReflect.Descriptor instead.
func (*IBPartitionId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{15}
}

func (x *IBPartitionId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type InstanceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceId) Reset() {
	*x = InstanceId{}
	mi := &file_common_nico_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceId) ProtoMessage() {}

func (x *InstanceId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceId.ProtoReflect.Descriptor instead.
func (*InstanceId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{16}
}

func (x *InstanceId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NetworkSegmentId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkSegmentId) Reset() {
	*x = NetworkSegmentId{}
	mi := &file_common_nico_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSegmentId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSegmentId) ProtoMessage() {}

func (x *NetworkSegmentId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSegmentId.ProtoReflect.Descriptor instead.
func (*NetworkSegmentId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{17}
}

func (x *NetworkSegmentId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DpaInterfaceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DpaInterfaceId) Reset() {
	*x = DpaInterfaceId{}
	mi := &file_common_nico_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DpaInterfaceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DpaInterfaceId) ProtoMessage() {}

func (x *DpaInterfaceId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DpaInterfaceId.ProtoReflect.Descriptor instead.
func (*DpaInterfaceId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{18}
}

func (x *DpaInterfaceId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NetworkPrefixId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPrefixId) Reset() {
	*x = NetworkPrefixId{}
	mi := &file_common_nico_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPrefixId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPrefixId) ProtoMessage() {}

func (x *NetworkPrefixId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPrefixId.ProtoReflect.Descriptor instead.
func (*NetworkPrefixId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{19}
}

func (x *NetworkPrefixId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RemediationId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemediationId) Reset() {
	*x = RemediationId{}
	mi := &file_common_nico_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemediationId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemediationId) ProtoMessage() {}

func (x *RemediationId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemediationId.ProtoReflect.Descriptor instead.
func (*RemediationId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{20}
}

func (x *RemediationId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NVLinkPartitionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NVLinkPartitionId) Reset() {
	*x = NVLinkPartitionId{}
	mi := &file_common_nico_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NVLinkPartitionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVLinkPartitionId) ProtoMessage() {}

func (x *NVLinkPartitionId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVLinkPartitionId.ProtoReflect.Descriptor instead.
func (*NVLinkPartitionId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{21}
}

func (x *NVLinkPartitionId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NVLinkLogicalPartitionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NVLinkLogicalPartitionId) Reset() {
	*x = NVLinkLogicalPartitionId{}
	mi := &file_common_nico_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NVLinkLogicalPartitionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVLinkLogicalPartitionId) ProtoMessage() {}

func (x *NVLinkLogicalPartitionId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVLinkLogicalPartitionId.ProtoReflect.Descriptor instead.
func (*NVLinkLogicalPartitionId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{22}
}

func (x *NVLinkLogicalPartitionId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NVLinkDomainId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NVLinkDomainId) Reset() {
	*x = NVLinkDomainId{}
	mi := &file_common_nico_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NVLinkDomainId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVLinkDomainId) ProtoMessage() {}

func (x *NVLinkDomainId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVLinkDomainId.ProtoReflect.Descriptor instead.
func (*NVLinkDomainId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{23}
}

func (x *NVLinkDomainId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ComputeAllocationId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeAllocationId) Reset() {
	*x = ComputeAllocationId{}
	mi := &file_common_nico_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeAllocationId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeAllocationId) ProtoMessage() {}

func (x *ComputeAllocationId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeAllocationId.ProtoReflect.Descriptor instead.
func (*ComputeAllocationId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{24}
}

func (x *ComputeAllocationId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SpxPartitionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpxPartitionId) Reset() {
	*x = SpxPartitionId{}
	mi := &file_common_nico_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpxPartitionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpxPartitionId) ProtoMessage() {}

func (x *SpxPartitionId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpxPartitionId.ProtoReflect.Descriptor instead.
func (*SpxPartitionId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{25}
}

func (x *SpxPartitionId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OperatingSystemId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatingSystemId) Reset() {
	*x = OperatingSystemId{}
	mi := &file_common_nico_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatingSystemId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatingSystemId) ProtoMessage() {}

func (x *OperatingSystemId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatingSystemId.ProtoReflect.Descriptor instead.
func (*OperatingSystemId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{26}
}

func (x *OperatingSystemId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type IpxeTemplateId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpxeTemplateId) Reset() {
	*x = IpxeTemplateId{}
	mi := &file_common_nico_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpxeTemplateId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpxeTemplateId) ProtoMessage() {}

func (x *IpxeTemplateId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpxeTemplateId.ProtoReflect.Descriptor instead.
func (*IpxeTemplateId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{27}
}

func (x *IpxeTemplateId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RackHardwareType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RackHardwareType) Reset() {
	*x = RackHardwareType{}
	mi := &file_common_nico_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RackHardwareType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RackHardwareType) ProtoMessage() {}

func (x *RackHardwareType) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RackHardwareType.ProtoReflect.Descriptor instead.
func (*RackHardwareType) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{28}
}

func (x *RackHardwareType) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MachineValidationId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineValidationId) Reset() {
	*x = MachineValidationId{}
	mi := &file_common_nico_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineValidationId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineValidationId) ProtoMessage() {}

func (x *MachineValidationId) ProtoReflect() protoreflect.Message {
	mi := &file_common_nico_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineValidationId.ProtoReflect.Descriptor instead.
func (*MachineValidationId) Descriptor() ([]byte, []int) {
	return file_common_nico_proto_rawDescGZIP(), []int{29}
}

func (x *MachineValidationId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_common_nico_proto protoreflect.FileDescriptor

var file_common_nico_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6e, 0x69, 0x63, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x1b, 0x0a, 0x09, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0d, 0x4d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0b, 0x6d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49,
	0x64, 0x52, 0x0a, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x73, 0x22, 0x22, 0x0a,
	0x0a, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x1c, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x1e, 0x0a, 0x0c, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x68, 0x65, 0x6c, 0x66, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x18, 0x0a, 0x06, 0x52, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x0d, 0x52, 0x61, 0x63,
	0x6b, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1a, 0x0a, 0x08, 0x53, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x0a, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x31, 0x0a, 0x0b, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x73, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x61, 0x73, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x6e, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x76, 0x6e, 0x69, 0x22, 0x20, 0x0a,
	0x08, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x2a, 0x0a, 0x12, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1d, 0x0a, 0x05, 0x56,
	0x70, 0x63, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x23, 0x0a, 0x0b, 0x56, 0x70,
	0x63, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x24, 0x0a, 0x0c, 0x56, 0x70, 0x63, 0x50, 0x65, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x0d, 0x49, 0x42, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x22, 0x0a, 0x0a,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x28, 0x0a, 0x10, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x26, 0x0a, 0x0e, 0x44, 0x70,
	0x61, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x27, 0x0a, 0x0f, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x0d, 0x52,
	0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x29, 0x0a, 0x11, 0x4e, 0x56, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x30, 0x0a,
	0x18, 0x4e, 0x56, 0x4c, 0x69, 0x6e, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x26, 0x0a, 0x0e, 0x4e, 0x56, 0x4c, 0x69, 0x6e, 0x6b, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2b, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x70, 0x75,
	0x74, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x26, 0x0a, 0x0e, 0x53, 0x70, 0x78, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x29, 0x0a, 0x11,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x26, 0x0a, 0x0e, 0x49, 0x70, 0x78, 0x65, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x28, 0x0a, 0x10, 0x52, 0x61, 0x63, 0x6b, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2b, 0x0a, 0x13, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x9e, 0x02, 0x0a, 0x12, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x20, 0x0a,
	0x1c, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x43, 0x4f,
	0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x1b, 0x0a, 0x17, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x5f,
	0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x5f, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x2a, 0x0a, 0x26,
	0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e,
	0x54, 0x52, 0x4f, 0x4c, 0x5f, 0x47, 0x52, 0x41, 0x43, 0x45, 0x46, 0x55, 0x4c, 0x5f, 0x53, 0x48,
	0x55, 0x54, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12, 0x22, 0x0a, 0x1e, 0x53, 0x59, 0x53, 0x54,
	0x45, 0x4d, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c,
	0x5f, 0x46, 0x4f, 0x52, 0x43, 0x45, 0x5f, 0x4f, 0x46, 0x46, 0x10, 0x03, 0x12, 0x29, 0x0a, 0x25,
	0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e,
	0x54, 0x52, 0x4f, 0x4c, 0x5f, 0x47, 0x52, 0x41, 0x43, 0x45, 0x46, 0x55, 0x4c, 0x5f, 0x52, 0x45,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x04, 0x12, 0x26, 0x0a, 0x22, 0x53, 0x59, 0x53, 0x54, 0x45,
	0x4d, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x5f,
	0x46, 0x4f, 0x52, 0x43, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x05, 0x12,
	0x26, 0x0a, 0x22, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x5f,
	0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x5f, 0x41, 0x43, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52,
	0x43, 0x59, 0x43, 0x4c, 0x45, 0x10, 0x06, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x56, 0x49, 0x44, 0x49, 0x41, 0x2f, 0x69, 0x6e, 0x66,
	0x72, 0x61, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x72, 0x65,
	0x73, 0x74, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2d,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_common_nico_proto_rawDescOnce sync.Once
	file_common_nico_proto_rawDescData []byte
)

func file_common_nico_proto_rawDescGZIP() []byte {
	file_common_nico_proto_rawDescOnce.Do(func() {
		file_common_nico_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_nico_proto_rawDesc), len(file_common_nico_proto_rawDesc)))
	})
	return file_common_nico_proto_rawDescData
}

var file_common_nico_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_nico_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_common_nico_proto_goTypes = []any{
	(SystemPowerControl)(0),          // 0: common.SystemPowerControl
	(*MachineId)(nil),                // 1: common.MachineId
	(*MachineIdList)(nil),            // 2: common.MachineIdList
	(*StringList)(nil),               // 3: common.StringList
	(*UUID)(nil),                     // 4: common.UUID
	(*PowerShelfId)(nil),             // 5: common.PowerShelfId
	(*RackId)(nil),                   // 6: common.RackId
	(*RackProfileId)(nil),            // 7: common.RackProfileId
	(*SwitchId)(nil),                 // 8: common.SwitchId
	(*Uint32List)(nil),               // 9: common.Uint32List
	(*RouteTarget)(nil),              // 10: common.RouteTarget
	(*DomainId)(nil),                 // 11: common.DomainId
	(*MachineInterfaceId)(nil),       // 12: common.MachineInterfaceId
	(*VpcId)(nil),                    // 13: common.VpcId
	(*VpcPrefixId)(nil),              // 14: common.VpcPrefixId
	(*VpcPeeringId)(nil),             // 15: common.VpcPeeringId
	(*IBPartitionId)(nil),            // 16: common.IBPartitionId
	(*InstanceId)(nil),               // 17: common.InstanceId
	(*NetworkSegmentId)(nil),         // 18: common.NetworkSegmentId
	(*DpaInterfaceId)(nil),           // 19: common.DpaInterfaceId
	(*NetworkPrefixId)(nil),          // 20: common.NetworkPrefixId
	(*RemediationId)(nil),            // 21: common.RemediationId
	(*NVLinkPartitionId)(nil),        // 22: common.NVLinkPartitionId
	(*NVLinkLogicalPartitionId)(nil), // 23: common.NVLinkLogicalPartitionId
	(*NVLinkDomainId)(nil),           // 24: common.NVLinkDomainId
	(*ComputeAllocationId)(nil),      // 25: common.ComputeAllocationId
	(*SpxPartitionId)(nil),           // 26: common.SpxPartitionId
	(*OperatingSystemId)(nil),        // 27: common.OperatingSystemId
	(*IpxeTemplateId)(nil),           // 28: common.IpxeTemplateId
	(*RackHardwareType)(nil),         // 29: common.RackHardwareType
	(*MachineValidationId)(nil),      // 30: common.MachineValidationId
}
var file_common_nico_proto_depIdxs = []int32{
	1, // 0: common.MachineIdList.machine_ids:type_name -> common.MachineId
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_nico_proto_init() }
func file_common_nico_proto_init() {
	if File_common_nico_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_nico_proto_rawDesc), len(file_common_nico_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_nico_proto_goTypes,
		DependencyIndexes: file_common_nico_proto_depIdxs,
		EnumInfos:         file_common_nico_proto_enumTypes,
		MessageInfos:      file_common_nico_proto_msgTypes,
	}.Build()
	File_common_nico_proto = out.File
	file_common_nico_proto_goTypes = nil
	file_common_nico_proto_depIdxs = nil
}
