// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: health_nico.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reports the aggregate health of a system or subsystem
type HealthReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies the source of the health report
	// This could e.g. be `nico-dpu-agent`, `nico-host-validation`,
	// or an override (e.g. `overrides.sre-team`)
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// The person or system (service) that triggered this health report.
	// For manually triggered reports (e.g. via web UI), this identifies the user.
	TriggeredBy *string `protobuf:"bytes,5,opt,name=triggered_by,json=triggeredBy,proto3,oneof" json:"triggered_by,omitempty"`
	// The time when this health status was observed.
	//
	// Clients submitting a health report can leave this field empty in order
	// to store the current time as timestamp.
	//
	// In case the HealthReport is derived by combining the reports of various
	// subsystems, the timestamp will relate to the oldest overall report.
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=observed_at,json=observedAt,proto3,oneof" json:"observed_at,omitempty"`
	// List of all successful health probes
	Successes []*HealthProbeSuccess `protobuf:"bytes,3,rep,name=successes,proto3" json:"successes,omitempty"`
	// List of all alerts that have been raised by health probes
	Alerts        []*HealthProbeAlert `protobuf:"bytes,4,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_health_nico_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_health_nico_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_health_nico_proto_rawDescGZIP(), []int{0}
}

func (x *HealthReport) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HealthReport) GetTriggeredBy() string {
	if x != nil && x.TriggeredBy != nil {
		return *x.TriggeredBy
	}
	return ""
}

func (x *HealthReport) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *HealthReport) GetSuccesses() []*HealthProbeSuccess {
	if x != nil {
		return x.Successes
	}
	return nil
}

func (x *HealthReport) GetAlerts() []*HealthProbeAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

// An alert that has been raised by a health-probe
type HealthProbeAlert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable ID of the health probe that raised an alert
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The component that the probe is targeting.
	// This could be e.g.
	//   - a physical component (e.g. a Fan probe might check various chassis fans)
	//   - a logical component (a check which probes whether disk space is available
	//     can list the volume name as target)
	//
	// The field is optional. It can be absent if the probe ID already fully
	// describes what is tested.
	//
	// Targets are useful if the same type of probe checks the health of multiple components.
	// If a health report lists multiple probes of the same type and with different targets,
	// then those probe/target combinations are treated individually.
	// E.g. the `in_alert_since` and `classifications` fields for each probe/target
	// combination are calculated individually when reports are merged.
	Target *string `protobuf:"bytes,6,opt,name=target,proto3,oneof" json:"target,omitempty"`
	// The first time the probe raised an alert
	// If this field is empty while the HealthReport is sent to nico-core-api
	// the behavior is as follows:
	// - If an alert of the same `id` was reported before, the timestamp of the
	// previous alert will be retained.
	// - If this is a new alert, the timestamp will be set to "now".
	InAlertSince *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=in_alert_since,json=inAlertSince,proto3,oneof" json:"in_alert_since,omitempty"`
	// A message that describes the alert
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// An optional message that will be relayed to tenants
	TenantMessage *string `protobuf:"bytes,4,opt,name=tenant_message,json=tenantMessage,proto3,oneof" json:"tenant_message,omitempty"`
	// Classifications for this alert
	// A string is used here to maintain flexibility
	Classifications []string `protobuf:"bytes,5,rep,name=classifications,proto3" json:"classifications,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthProbeAlert) Reset() {
	*x = HealthProbeAlert{}
	mi := &file_health_nico_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthProbeAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthProbeAlert) ProtoMessage() {}

func (x *HealthProbeAlert) ProtoReflect() protoreflect.Message {
	mi := &file_health_nico_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthProbeAlert.ProtoReflect.Descriptor instead.
func (*HealthProbeAlert) Descriptor() ([]byte, []int) {
	return file_health_nico_proto_rawDescGZIP(), []int{1}
}

func (x *HealthProbeAlert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HealthProbeAlert) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *HealthProbeAlert) GetInAlertSince() *timestamppb.Timestamp {
	if x != nil {
		return x.InAlertSince
	}
	return nil
}

func (x *HealthProbeAlert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthProbeAlert) GetTenantMessage() string {
	if x != nil && x.TenantMessage != nil {
		return *x.TenantMessage
	}
	return ""
}

func (x *HealthProbeAlert) GetClassifications() []string {
	if x != nil {
		return x.Classifications
	}
	return nil
}

// A successful health probe (reported no alerts)
type HealthProbeSuccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable ID of the health probe that succeeded
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The component that the probe is targeting.
	// This could be e.g.
	//   - a physical component (e.g. a Fan probe might check various chassis fans)
	//   - a logical component (a check which probes whether disk space is available
	//     can list the volume name as target)
	//
	// The field is optional. It can be absent if the probe ID already fully
	// describes what is tested.
	//
	// Targets are useful if the same type of probe checks the health of multiple components.
	// If a health report lists multiple probes of the same type and with different targets,
	// then those probe/target combinations are treated individually.
	// E.g. the `in_alert_since` and `classifications` fields for each probe/target
	// combination are calculated individually when reports are merged.
	Target        *string `protobuf:"bytes,2,opt,name=target,proto3,oneof" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthProbeSuccess) Reset() {
	*x = HealthProbeSuccess{}
	mi := &file_health_nico_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthProbeSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthProbeSuccess) ProtoMessage() {}

func (x *HealthProbeSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_health_nico_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthProbeSuccess.ProtoReflect.Descriptor instead.
func (*HealthProbeSuccess) Descriptor() ([]byte, []int) {
	return file_health_nico_proto_rawDescGZIP(), []int{2}
}

func (x *HealthProbeSuccess) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HealthProbeSuccess) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

var File_health_nico_proto protoreflect.FileDescriptor

var file_health_nico_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x6e, 0x69, 0x63, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x1a, 0x1e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x02, 0x0a, 0x0c, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x26, 0x0a, 0x0c, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x65, 0x64, 0x5f,
	0x62, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x65, 0x64, 0x42, 0x79, 0x88, 0x01, 0x01, 0x12, 0x40, 0x0a, 0x0b, 0x6f, 0x62,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x01, 0x52, 0x0a, 0x6f,
	0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x41, 0x74, 0x88, 0x01, 0x01, 0x12, 0x38, 0x0a, 0x09,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x50,
	0x72, 0x6f, 0x62, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x09, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2e,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x41, 0x6c, 0x65, 0x72, 0x74,
	0x52, 0x06, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x74, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6f, 0x62,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x22, 0xa7, 0x02, 0x0a, 0x10, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b,
	0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12, 0x45, 0x0a, 0x0e, 0x69,
	0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48,
	0x01, 0x52, 0x0c, 0x69, 0x6e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x53, 0x69, 0x6e, 0x63, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x0e,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0d, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42, 0x11, 0x0a,
	0x0f, 0x5f, 0x69, 0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x73, 0x69, 0x6e, 0x63, 0x65,
	0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x4c, 0x0a, 0x12, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x50, 0x72, 0x6f,
	0x62, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4e, 0x56, 0x49, 0x44, 0x49, 0x41, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2d, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x2d, 0x61, 0x70, 0x69,
	0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2d, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_health_nico_proto_rawDescOnce sync.Once
	file_health_nico_proto_rawDescData []byte
)

func file_health_nico_proto_rawDescGZIP() []byte {
	file_health_nico_proto_rawDescOnce.Do(func() {
		file_health_nico_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_nico_proto_rawDesc), len(file_health_nico_proto_rawDesc)))
	})
	return file_health_nico_proto_rawDescData
}

var file_health_nico_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_health_nico_proto_goTypes = []any{
	(*HealthReport)(nil),          // 0: health.HealthReport
	(*HealthProbeAlert)(nil),      // 1: health.HealthProbeAlert
	(*HealthProbeSuccess)(nil),    // 2: health.HealthProbeSuccess
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_health_nico_proto_depIdxs = []int32{
	3, // 0: health.HealthReport.observed_at:type_name -> google.protobuf.Timestamp
	2, // 1: health.HealthReport.successes:type_name -> health.HealthProbeSuccess
	1, // 2: health.HealthReport.alerts:type_name -> health.HealthProbeAlert
	3, // 3: health.HealthProbeAlert.in_alert_since:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_health_nico_proto_init() }
func file_health_nico_proto_init() {
	if File_health_nico_proto != nil {
		return
	}
	file_health_nico_proto_msgTypes[0].OneofWrappers = []any{}
	file_health_nico_proto_msgTypes[1].OneofWrappers = []any{}
	file_health_nico_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_nico_proto_rawDesc), len(file_health_nico_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_health_nico_proto_goTypes,
		DependencyIndexes: file_health_nico_proto_depIdxs,
		MessageInfos:      file_health_nico_proto_msgTypes,
	}.Build()
	File_health_nico_proto = out.File
	file_health_nico_proto_goTypes = nil
	file_health_nico_proto_depIdxs = nil
}
