/*
 *   SPDX-FileCopyrightText: Copyright (c) 2022-2022. NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 *   SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 *
 *   NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 *   property and proprietary rights in and to this material, related
 *   documentation and any modifications thereto. Any use, reproduction,
 *   disclosure or distribution of this material and related documentation
 *   without an express license agreement from NVIDIA CORPORATION or
 *   its affiliates is strictly prohibited.
 */

use std::{net::Ipv4Addr, process::Command};

use gtmpl_derive::Gtmpl;

pub const PATH: &str = "/etc/supervisor/conf.d/default-isc-dhcp-relay.conf";
pub const PATH_NEXT: &str = "/tmp/default-isc-dhcp-relay.conf.NEXT";
const _TMPL_EMPTY: &str = "# Auto-generated by Forge!";
const TMPL_FULL: &str = include_str!("../templates/default-isc-dhcp-relay.conf");

/// Generate default-isc-dhcp-relay.conf
pub fn build(conf: DhcpConfig) -> Result<String, eyre::Report> {
    let params = TmplDHCRelayConfigParameters {
        Uplinks: conf.uplinks,
        VlanIDs: conf.vlan_ids,
        Servers: conf.dhcp_servers.iter().map(|ip| ip.to_string()).collect(),
    };
    gtmpl::template(TMPL_FULL, params).map_err(|e| e.into())
}

pub fn reload() -> Result<(), eyre::Report> {
    let out = Command::new("supervisorctl").arg("update").output()?;
    if !out.status.success() {
        return Err(eyre::eyre!(
            "Failed reloading DHCP relay with 'supervisorctl update'. \nSTDOUT: {}\nSTDERR: {}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr),
        ));
    }
    Ok(())
}

pub struct DhcpConfig {
    pub uplinks: Vec<String>,
    pub vlan_ids: Vec<u32>,
    pub dhcp_servers: Vec<Ipv4Addr>,
}

//
// Go template object, hence allow(non_snake_case)
//

#[allow(non_snake_case)]
#[derive(Clone, Gtmpl)]
struct TmplDHCRelayConfigParameters {
    Uplinks: Vec<String>,
    VlanIDs: Vec<u32>,
    Servers: Vec<String>,
}

#[cfg(test)]
mod tests {
    use super::{build, DhcpConfig};

    #[test]
    fn test_write_dhcp() -> Result<(), Box<dyn std::error::Error>> {
        let params = DhcpConfig {
            uplinks: vec!["p0_sf".to_string(), "p1_sf".to_string()],
            vlan_ids: vec![177],
            dhcp_servers: vec![[10, 180, 248, 25].into()],
        };
        let output = build(params)?;
        assert_eq!(
            output,
            include_str!("../templates/default-isc-dhcp-relay.conf.expected")
        );
        Ok(())
    }
}
