#!/bin/sh

set -e
export PATH=/usr/lib/postgresql/14/bin:$PATH  

host="$1"
shift
rootdir="$1"
shift
migration_count=$1
shift

POSTGRES_USER="carbide_development"
POSTGRES_PASSWORD="notforprod"

until PGPASSWORD=$POSTGRES_PASSWORD psql -h "$host" -U "${POSTGRES_USER}" -c '\q'; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done
>&2 echo "Postgres is up"

sleep 5 #cheating

cur=0
until [ $cur -eq $migration_count ]; do
  cur=$(PGPASSWORD=$POSTGRES_PASSWORD psql --no-align --tuples-only -h $host -U $POSTGRES_USER -c "select count(*) from _sqlx_migrations")
  echo $initial
  >&2 echo "Migrations not applied - sleeping"
  sleep 1
done
cd $rootdir 
>&2 echo "Carbide DB migrations completed - executing command"
exec "$@"
