#!/bin/sh

export PATH=/usr/lib/postgresql/14/bin:$PATH
set -e
  
host="$1"
shift
rootdir="$1"
shift
  
until PGPASSWORD=$POSTGRES_PASSWORD psql -h "$host" -U "${POSTGRES_USER}" -c '\q'; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done
  
>&2 echo "Postgres is up - executing command"
cd $rootdir
pwd
exec "$@"
