# syntax=docker/dockerfile:1.4

# SPDX-FileCopyrightText: Copyright (c) 2021-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
FROM urm.nvidia.com/swngc-ngcc-docker-local/forge/carbide/x86-64/build-container:v0.0.1-470-g80a16ba9 as builder
WORKDIR ./carbide
COPY . ./
ENV RUSTC_WRAPPER=/usr/local/cargo/bin/sccache
ENV SCCACHE_CACHE_SIZE 2G
ENV SCCACHE_DIR /root/.cache/sccache
RUN --mount=type=cache,target=/root/.cache/sccache --mount=type=cache,target=/usr/local/cargo/registry/ cargo build -p dhcp && sccache --show-stats

FROM ubuntu:focal as carbide
RUN mkdir -p /opt/carbide/migrations && \
  mkdir -p /opt/carbide/pxe/templates && \
  mkdir -p /opt/carbide/static
RUN --mount=type=cache,target=/var/cache/apt apt-get update && apt-get install -y --no-install-recommends \
  ca-certificates curl iproute2
COPY dev/deployment/pgdg.gpg /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg
COPY dev/deployment/pgdg.list /etc/apt/sources.list.d/pgdg.list
COPY dev/deployment/isc-kea-2-0.gpg /etc/apt/trusted.gpg.d/apt.isc-kea-2.0.gpg
COPY dev/deployment/isc-kea-2-0.list /etc/apt/sources.list.d/isc-kea-2.0.list
RUN --mount=type=cache,target=/var/cache/apt apt-get update && apt-get install -y --no-install-recommends \
  postgresql-client-14 postgresql-client-14-dbgsym \
  ca-certificates curl iproute2 iputils-ping \
  isc-kea-dhcp4-server isc-kea-dhcp6-server libudev1
COPY --from=builder /carbide/target/debug/libdhcp.so /usr/lib/x86_64-linux-gnu/kea/hooks
