#!/bin/sh
set -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then
	systemctl enable local_bmc_dev.service
	systemctl enable forge-dpu-agent.service
	systemctl start forge-dpu-agent
fi
