/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CampaignFirmwareOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignFirmwareOperation{}

// CampaignFirmwareOperation Configures a firmware rollout.
type CampaignFirmwareOperation struct {
	// Target firmware version to roll out.
	Version string `json:"version"`
	// Operation Rule to pin for each target's firmware Task. Null to let Flow's default rule resolution pick one.
	RuleId NullableString `json:"ruleId,omitempty"`
	// Skip the pre-flight readiness check when true.
	OverrideReadinessCheck *bool `json:"overrideReadinessCheck,omitempty"`
	// Optional subset of firmware sub-targets to update.
	SubTargets []string `json:"subTargets,omitempty"`
}

type _CampaignFirmwareOperation CampaignFirmwareOperation

// NewCampaignFirmwareOperation instantiates a new CampaignFirmwareOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignFirmwareOperation(version string) *CampaignFirmwareOperation {
	this := CampaignFirmwareOperation{}
	this.Version = version
	var overrideReadinessCheck bool = false
	this.OverrideReadinessCheck = &overrideReadinessCheck
	return &this
}

// NewCampaignFirmwareOperationWithDefaults instantiates a new CampaignFirmwareOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignFirmwareOperationWithDefaults() *CampaignFirmwareOperation {
	this := CampaignFirmwareOperation{}
	var overrideReadinessCheck bool = false
	this.OverrideReadinessCheck = &overrideReadinessCheck
	return &this
}

// GetVersion returns the Version field value
func (o *CampaignFirmwareOperation) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *CampaignFirmwareOperation) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *CampaignFirmwareOperation) SetVersion(v string) {
	o.Version = v
}

// GetRuleId returns the RuleId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CampaignFirmwareOperation) GetRuleId() string {
	if o == nil || IsNil(o.RuleId.Get()) {
		var ret string
		return ret
	}
	return *o.RuleId.Get()
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CampaignFirmwareOperation) GetRuleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RuleId.Get(), o.RuleId.IsSet()
}

// HasRuleId returns a boolean if a field has been set.
func (o *CampaignFirmwareOperation) HasRuleId() bool {
	if o != nil && o.RuleId.IsSet() {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given NullableString and assigns it to the RuleId field.
func (o *CampaignFirmwareOperation) SetRuleId(v string) {
	o.RuleId.Set(&v)
}

// SetRuleIdNil sets the value for RuleId to be an explicit nil
func (o *CampaignFirmwareOperation) SetRuleIdNil() {
	o.RuleId.Set(nil)
}

// UnsetRuleId ensures that no value is present for RuleId, not even an explicit nil
func (o *CampaignFirmwareOperation) UnsetRuleId() {
	o.RuleId.Unset()
}

// GetOverrideReadinessCheck returns the OverrideReadinessCheck field value if set, zero value otherwise.
func (o *CampaignFirmwareOperation) GetOverrideReadinessCheck() bool {
	if o == nil || IsNil(o.OverrideReadinessCheck) {
		var ret bool
		return ret
	}
	return *o.OverrideReadinessCheck
}

// GetOverrideReadinessCheckOk returns a tuple with the OverrideReadinessCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignFirmwareOperation) GetOverrideReadinessCheckOk() (*bool, bool) {
	if o == nil || IsNil(o.OverrideReadinessCheck) {
		return nil, false
	}
	return o.OverrideReadinessCheck, true
}

// HasOverrideReadinessCheck returns a boolean if a field has been set.
func (o *CampaignFirmwareOperation) HasOverrideReadinessCheck() bool {
	if o != nil && !IsNil(o.OverrideReadinessCheck) {
		return true
	}

	return false
}

// SetOverrideReadinessCheck gets a reference to the given bool and assigns it to the OverrideReadinessCheck field.
func (o *CampaignFirmwareOperation) SetOverrideReadinessCheck(v bool) {
	o.OverrideReadinessCheck = &v
}

// GetSubTargets returns the SubTargets field value if set, zero value otherwise.
func (o *CampaignFirmwareOperation) GetSubTargets() []string {
	if o == nil || IsNil(o.SubTargets) {
		var ret []string
		return ret
	}
	return o.SubTargets
}

// GetSubTargetsOk returns a tuple with the SubTargets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignFirmwareOperation) GetSubTargetsOk() ([]string, bool) {
	if o == nil || IsNil(o.SubTargets) {
		return nil, false
	}
	return o.SubTargets, true
}

// HasSubTargets returns a boolean if a field has been set.
func (o *CampaignFirmwareOperation) HasSubTargets() bool {
	if o != nil && !IsNil(o.SubTargets) {
		return true
	}

	return false
}

// SetSubTargets gets a reference to the given []string and assigns it to the SubTargets field.
func (o *CampaignFirmwareOperation) SetSubTargets(v []string) {
	o.SubTargets = v
}

func (o CampaignFirmwareOperation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignFirmwareOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	if o.RuleId.IsSet() {
		toSerialize["ruleId"] = o.RuleId.Get()
	}
	if !IsNil(o.OverrideReadinessCheck) {
		toSerialize["overrideReadinessCheck"] = o.OverrideReadinessCheck
	}
	if !IsNil(o.SubTargets) {
		toSerialize["subTargets"] = o.SubTargets
	}
	return toSerialize, nil
}

func (o *CampaignFirmwareOperation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCampaignFirmwareOperation := _CampaignFirmwareOperation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCampaignFirmwareOperation)

	if err != nil {
		return err
	}

	*o = CampaignFirmwareOperation(varCampaignFirmwareOperation)

	return err
}

type NullableCampaignFirmwareOperation struct {
	value *CampaignFirmwareOperation
	isSet bool
}

func (v NullableCampaignFirmwareOperation) Get() *CampaignFirmwareOperation {
	return v.value
}

func (v *NullableCampaignFirmwareOperation) Set(val *CampaignFirmwareOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignFirmwareOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignFirmwareOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignFirmwareOperation(val *CampaignFirmwareOperation) *NullableCampaignFirmwareOperation {
	return &NullableCampaignFirmwareOperation{value: val, isSet: true}
}

func (v NullableCampaignFirmwareOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignFirmwareOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
