// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RunFailureCountGate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunFailureCountGate{}

// RunFailureCountGate Pauses when the number of failed targets reaches `thresholdCount` for the scope.
type RunFailureCountGate struct {
	// Whether the count is evaluated over the current phase or the cumulative run.
	Scope *string `json:"scope,omitempty"`
	// Number of failed targets at which the gate trips.
	ThresholdCount int32 `json:"thresholdCount"`
}

type _RunFailureCountGate RunFailureCountGate

// NewRunFailureCountGate instantiates a new RunFailureCountGate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunFailureCountGate(thresholdCount int32) *RunFailureCountGate {
	this := RunFailureCountGate{}
	var scope string = "currentPhase"
	this.Scope = &scope
	this.ThresholdCount = thresholdCount
	return &this
}

// NewRunFailureCountGateWithDefaults instantiates a new RunFailureCountGate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunFailureCountGateWithDefaults() *RunFailureCountGate {
	this := RunFailureCountGate{}
	var scope string = "currentPhase"
	this.Scope = &scope
	return &this
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *RunFailureCountGate) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunFailureCountGate) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *RunFailureCountGate) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *RunFailureCountGate) SetScope(v string) {
	o.Scope = &v
}

// GetThresholdCount returns the ThresholdCount field value
func (o *RunFailureCountGate) GetThresholdCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ThresholdCount
}

// GetThresholdCountOk returns a tuple with the ThresholdCount field value
// and a boolean to check if the value has been set.
func (o *RunFailureCountGate) GetThresholdCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThresholdCount, true
}

// SetThresholdCount sets field value
func (o *RunFailureCountGate) SetThresholdCount(v int32) {
	o.ThresholdCount = v
}

func (o RunFailureCountGate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunFailureCountGate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	toSerialize["thresholdCount"] = o.ThresholdCount
	return toSerialize, nil
}

func (o *RunFailureCountGate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"thresholdCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRunFailureCountGate := _RunFailureCountGate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRunFailureCountGate)

	if err != nil {
		return err
	}

	*o = RunFailureCountGate(varRunFailureCountGate)

	return err
}

type NullableRunFailureCountGate struct {
	value *RunFailureCountGate
	isSet bool
}

func (v NullableRunFailureCountGate) Get() *RunFailureCountGate {
	return v.value
}

func (v *NullableRunFailureCountGate) Set(val *RunFailureCountGate) {
	v.value = val
	v.isSet = true
}

func (v NullableRunFailureCountGate) IsSet() bool {
	return v.isSet
}

func (v *NullableRunFailureCountGate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunFailureCountGate(val *RunFailureCountGate) *NullableRunFailureCountGate {
	return &NullableRunFailureCountGate{value: val, isSet: true}
}

func (v NullableRunFailureCountGate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunFailureCountGate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
