// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TenantRoutingProfiles type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantRoutingProfiles{}

// TenantRoutingProfiles Site-scoped VPC routing profiles available to the current Tenant
type TenantRoutingProfiles struct {
	// Routing profile applied by Core when a VPC omits routingProfile
	TenantDefaultRoutingProfile string `json:"tenantDefaultRoutingProfile"`
	// Site-configured routing profiles the Tenant may choose at this Site. Choosing `tenantDefaultRoutingProfile` inherits it by omitting `routingProfile`; other returned values can be sent explicitly when creating a VPC.
	PermittedRoutingProfiles []string `json:"permittedRoutingProfiles"`
}

type _TenantRoutingProfiles TenantRoutingProfiles

// NewTenantRoutingProfiles instantiates a new TenantRoutingProfiles object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantRoutingProfiles(tenantDefaultRoutingProfile string, permittedRoutingProfiles []string) *TenantRoutingProfiles {
	this := TenantRoutingProfiles{}
	this.TenantDefaultRoutingProfile = tenantDefaultRoutingProfile
	this.PermittedRoutingProfiles = permittedRoutingProfiles
	return &this
}

// NewTenantRoutingProfilesWithDefaults instantiates a new TenantRoutingProfiles object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantRoutingProfilesWithDefaults() *TenantRoutingProfiles {
	this := TenantRoutingProfiles{}
	return &this
}

// GetTenantDefaultRoutingProfile returns the TenantDefaultRoutingProfile field value
func (o *TenantRoutingProfiles) GetTenantDefaultRoutingProfile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantDefaultRoutingProfile
}

// GetTenantDefaultRoutingProfileOk returns a tuple with the TenantDefaultRoutingProfile field value
// and a boolean to check if the value has been set.
func (o *TenantRoutingProfiles) GetTenantDefaultRoutingProfileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantDefaultRoutingProfile, true
}

// SetTenantDefaultRoutingProfile sets field value
func (o *TenantRoutingProfiles) SetTenantDefaultRoutingProfile(v string) {
	o.TenantDefaultRoutingProfile = v
}

// GetPermittedRoutingProfiles returns the PermittedRoutingProfiles field value
func (o *TenantRoutingProfiles) GetPermittedRoutingProfiles() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.PermittedRoutingProfiles
}

// GetPermittedRoutingProfilesOk returns a tuple with the PermittedRoutingProfiles field value
// and a boolean to check if the value has been set.
func (o *TenantRoutingProfiles) GetPermittedRoutingProfilesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PermittedRoutingProfiles, true
}

// SetPermittedRoutingProfiles sets field value
func (o *TenantRoutingProfiles) SetPermittedRoutingProfiles(v []string) {
	o.PermittedRoutingProfiles = v
}

func (o TenantRoutingProfiles) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantRoutingProfiles) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantDefaultRoutingProfile"] = o.TenantDefaultRoutingProfile
	toSerialize["permittedRoutingProfiles"] = o.PermittedRoutingProfiles
	return toSerialize, nil
}

func (o *TenantRoutingProfiles) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantDefaultRoutingProfile",
		"permittedRoutingProfiles",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantRoutingProfiles := _TenantRoutingProfiles{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varTenantRoutingProfiles)

	if err != nil {
		return err
	}

	*o = TenantRoutingProfiles(varTenantRoutingProfiles)

	return err
}

type NullableTenantRoutingProfiles struct {
	value *TenantRoutingProfiles
	isSet bool
}

func (v NullableTenantRoutingProfiles) Get() *TenantRoutingProfiles {
	return v.value
}

func (v *NullableTenantRoutingProfiles) Set(val *TenantRoutingProfiles) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantRoutingProfiles) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantRoutingProfiles) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantRoutingProfiles(val *TenantRoutingProfiles) *NullableTenantRoutingProfiles {
	return &NullableTenantRoutingProfiles{value: val, isSet: true}
}

func (v NullableTenantRoutingProfiles) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantRoutingProfiles) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
