// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MeasurementTrustedMachineCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeasurementTrustedMachineCreateRequest{}

// MeasurementTrustedMachineCreateRequest Request to approve a Machine for automatic promotion of measured-boot reports.
type MeasurementTrustedMachineCreateRequest struct {
	// ID of the Site where the approval applies.
	SiteId string `json:"siteId"`
	// Machine UUID, or `*` to approve all Machines at the Site.
	MachineId string `json:"machineId"`
	// Whether the approval is consumed once or persists for future reports.
	ApprovalType string `json:"approvalType"`
	// Optional comma-separated PCR register selector. All registers are used when omitted.
	PcrRegisters *string `json:"pcrRegisters,omitempty"`
	// Optional operator comments about the approval.
	Comments *string `json:"comments,omitempty"`
}

type _MeasurementTrustedMachineCreateRequest MeasurementTrustedMachineCreateRequest

// NewMeasurementTrustedMachineCreateRequest instantiates a new MeasurementTrustedMachineCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeasurementTrustedMachineCreateRequest(siteId string, machineId string, approvalType string) *MeasurementTrustedMachineCreateRequest {
	this := MeasurementTrustedMachineCreateRequest{}
	this.SiteId = siteId
	this.MachineId = machineId
	this.ApprovalType = approvalType
	return &this
}

// NewMeasurementTrustedMachineCreateRequestWithDefaults instantiates a new MeasurementTrustedMachineCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeasurementTrustedMachineCreateRequestWithDefaults() *MeasurementTrustedMachineCreateRequest {
	this := MeasurementTrustedMachineCreateRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *MeasurementTrustedMachineCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *MeasurementTrustedMachineCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *MeasurementTrustedMachineCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetMachineId returns the MachineId field value
func (o *MeasurementTrustedMachineCreateRequest) GetMachineId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MachineId
}

// GetMachineIdOk returns a tuple with the MachineId field value
// and a boolean to check if the value has been set.
func (o *MeasurementTrustedMachineCreateRequest) GetMachineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MachineId, true
}

// SetMachineId sets field value
func (o *MeasurementTrustedMachineCreateRequest) SetMachineId(v string) {
	o.MachineId = v
}

// GetApprovalType returns the ApprovalType field value
func (o *MeasurementTrustedMachineCreateRequest) GetApprovalType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApprovalType
}

// GetApprovalTypeOk returns a tuple with the ApprovalType field value
// and a boolean to check if the value has been set.
func (o *MeasurementTrustedMachineCreateRequest) GetApprovalTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApprovalType, true
}

// SetApprovalType sets field value
func (o *MeasurementTrustedMachineCreateRequest) SetApprovalType(v string) {
	o.ApprovalType = v
}

// GetPcrRegisters returns the PcrRegisters field value if set, zero value otherwise.
func (o *MeasurementTrustedMachineCreateRequest) GetPcrRegisters() string {
	if o == nil || IsNil(o.PcrRegisters) {
		var ret string
		return ret
	}
	return *o.PcrRegisters
}

// GetPcrRegistersOk returns a tuple with the PcrRegisters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeasurementTrustedMachineCreateRequest) GetPcrRegistersOk() (*string, bool) {
	if o == nil || IsNil(o.PcrRegisters) {
		return nil, false
	}
	return o.PcrRegisters, true
}

// HasPcrRegisters returns a boolean if a field has been set.
func (o *MeasurementTrustedMachineCreateRequest) HasPcrRegisters() bool {
	if o != nil && !IsNil(o.PcrRegisters) {
		return true
	}

	return false
}

// SetPcrRegisters gets a reference to the given string and assigns it to the PcrRegisters field.
func (o *MeasurementTrustedMachineCreateRequest) SetPcrRegisters(v string) {
	o.PcrRegisters = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *MeasurementTrustedMachineCreateRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeasurementTrustedMachineCreateRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *MeasurementTrustedMachineCreateRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *MeasurementTrustedMachineCreateRequest) SetComments(v string) {
	o.Comments = &v
}

func (o MeasurementTrustedMachineCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeasurementTrustedMachineCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["machineId"] = o.MachineId
	toSerialize["approvalType"] = o.ApprovalType
	if !IsNil(o.PcrRegisters) {
		toSerialize["pcrRegisters"] = o.PcrRegisters
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	return toSerialize, nil
}

func (o *MeasurementTrustedMachineCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"machineId",
		"approvalType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeasurementTrustedMachineCreateRequest := _MeasurementTrustedMachineCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeasurementTrustedMachineCreateRequest)

	if err != nil {
		return err
	}

	*o = MeasurementTrustedMachineCreateRequest(varMeasurementTrustedMachineCreateRequest)

	return err
}

type NullableMeasurementTrustedMachineCreateRequest struct {
	value *MeasurementTrustedMachineCreateRequest
	isSet bool
}

func (v NullableMeasurementTrustedMachineCreateRequest) Get() *MeasurementTrustedMachineCreateRequest {
	return v.value
}

func (v *NullableMeasurementTrustedMachineCreateRequest) Set(val *MeasurementTrustedMachineCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMeasurementTrustedMachineCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMeasurementTrustedMachineCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeasurementTrustedMachineCreateRequest(val *MeasurementTrustedMachineCreateRequest) *NullableMeasurementTrustedMachineCreateRequest {
	return &NullableMeasurementTrustedMachineCreateRequest{value: val, isSet: true}
}

func (v NullableMeasurementTrustedMachineCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeasurementTrustedMachineCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
