/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CampaignFailureCountGate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignFailureCountGate{}

// CampaignFailureCountGate Pauses when the number of failed targets reaches `thresholdCount` for the scope.
type CampaignFailureCountGate struct {
	// Whether the count is evaluated over the current phase or the cumulative run.
	Scope *string `json:"scope,omitempty"`
	// Number of failed targets at which the gate trips.
	ThresholdCount int32 `json:"thresholdCount"`
}

type _CampaignFailureCountGate CampaignFailureCountGate

// NewCampaignFailureCountGate instantiates a new CampaignFailureCountGate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignFailureCountGate(thresholdCount int32) *CampaignFailureCountGate {
	this := CampaignFailureCountGate{}
	var scope string = "currentPhase"
	this.Scope = &scope
	this.ThresholdCount = thresholdCount
	return &this
}

// NewCampaignFailureCountGateWithDefaults instantiates a new CampaignFailureCountGate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignFailureCountGateWithDefaults() *CampaignFailureCountGate {
	this := CampaignFailureCountGate{}
	var scope string = "currentPhase"
	this.Scope = &scope
	return &this
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *CampaignFailureCountGate) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignFailureCountGate) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *CampaignFailureCountGate) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *CampaignFailureCountGate) SetScope(v string) {
	o.Scope = &v
}

// GetThresholdCount returns the ThresholdCount field value
func (o *CampaignFailureCountGate) GetThresholdCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ThresholdCount
}

// GetThresholdCountOk returns a tuple with the ThresholdCount field value
// and a boolean to check if the value has been set.
func (o *CampaignFailureCountGate) GetThresholdCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThresholdCount, true
}

// SetThresholdCount sets field value
func (o *CampaignFailureCountGate) SetThresholdCount(v int32) {
	o.ThresholdCount = v
}

func (o CampaignFailureCountGate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignFailureCountGate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	toSerialize["thresholdCount"] = o.ThresholdCount
	return toSerialize, nil
}

func (o *CampaignFailureCountGate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"thresholdCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCampaignFailureCountGate := _CampaignFailureCountGate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCampaignFailureCountGate)

	if err != nil {
		return err
	}

	*o = CampaignFailureCountGate(varCampaignFailureCountGate)

	return err
}

type NullableCampaignFailureCountGate struct {
	value *CampaignFailureCountGate
	isSet bool
}

func (v NullableCampaignFailureCountGate) Get() *CampaignFailureCountGate {
	return v.value
}

func (v *NullableCampaignFailureCountGate) Set(val *CampaignFailureCountGate) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignFailureCountGate) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignFailureCountGate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignFailureCountGate(val *CampaignFailureCountGate) *NullableCampaignFailureCountGate {
	return &NullableCampaignFailureCountGate{value: val, isSet: true}
}

func (v NullableCampaignFailureCountGate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignFailureCountGate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
