// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the RunConflictRetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunConflictRetry{}

// RunConflictRetry Retry backoff for blocked targets. Durations are Go duration strings (e.g. `30m`, `10s`); an empty value means \"use the operation default\".
type RunConflictRetry struct {
	// Total time to keep retrying a blocked target before giving up.
	RetryTimeout *string `json:"retryTimeout,omitempty"`
	// Delay before the first retry.
	InitialRetryDelay *string `json:"initialRetryDelay,omitempty"`
	// Cap on the exponentially growing retry delay.
	MaxRetryDelay *string `json:"maxRetryDelay,omitempty"`
}

// NewRunConflictRetry instantiates a new RunConflictRetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunConflictRetry() *RunConflictRetry {
	this := RunConflictRetry{}
	return &this
}

// NewRunConflictRetryWithDefaults instantiates a new RunConflictRetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunConflictRetryWithDefaults() *RunConflictRetry {
	this := RunConflictRetry{}
	return &this
}

// GetRetryTimeout returns the RetryTimeout field value if set, zero value otherwise.
func (o *RunConflictRetry) GetRetryTimeout() string {
	if o == nil || IsNil(o.RetryTimeout) {
		var ret string
		return ret
	}
	return *o.RetryTimeout
}

// GetRetryTimeoutOk returns a tuple with the RetryTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunConflictRetry) GetRetryTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.RetryTimeout) {
		return nil, false
	}
	return o.RetryTimeout, true
}

// HasRetryTimeout returns a boolean if a field has been set.
func (o *RunConflictRetry) HasRetryTimeout() bool {
	if o != nil && !IsNil(o.RetryTimeout) {
		return true
	}

	return false
}

// SetRetryTimeout gets a reference to the given string and assigns it to the RetryTimeout field.
func (o *RunConflictRetry) SetRetryTimeout(v string) {
	o.RetryTimeout = &v
}

// GetInitialRetryDelay returns the InitialRetryDelay field value if set, zero value otherwise.
func (o *RunConflictRetry) GetInitialRetryDelay() string {
	if o == nil || IsNil(o.InitialRetryDelay) {
		var ret string
		return ret
	}
	return *o.InitialRetryDelay
}

// GetInitialRetryDelayOk returns a tuple with the InitialRetryDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunConflictRetry) GetInitialRetryDelayOk() (*string, bool) {
	if o == nil || IsNil(o.InitialRetryDelay) {
		return nil, false
	}
	return o.InitialRetryDelay, true
}

// HasInitialRetryDelay returns a boolean if a field has been set.
func (o *RunConflictRetry) HasInitialRetryDelay() bool {
	if o != nil && !IsNil(o.InitialRetryDelay) {
		return true
	}

	return false
}

// SetInitialRetryDelay gets a reference to the given string and assigns it to the InitialRetryDelay field.
func (o *RunConflictRetry) SetInitialRetryDelay(v string) {
	o.InitialRetryDelay = &v
}

// GetMaxRetryDelay returns the MaxRetryDelay field value if set, zero value otherwise.
func (o *RunConflictRetry) GetMaxRetryDelay() string {
	if o == nil || IsNil(o.MaxRetryDelay) {
		var ret string
		return ret
	}
	return *o.MaxRetryDelay
}

// GetMaxRetryDelayOk returns a tuple with the MaxRetryDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunConflictRetry) GetMaxRetryDelayOk() (*string, bool) {
	if o == nil || IsNil(o.MaxRetryDelay) {
		return nil, false
	}
	return o.MaxRetryDelay, true
}

// HasMaxRetryDelay returns a boolean if a field has been set.
func (o *RunConflictRetry) HasMaxRetryDelay() bool {
	if o != nil && !IsNil(o.MaxRetryDelay) {
		return true
	}

	return false
}

// SetMaxRetryDelay gets a reference to the given string and assigns it to the MaxRetryDelay field.
func (o *RunConflictRetry) SetMaxRetryDelay(v string) {
	o.MaxRetryDelay = &v
}

func (o RunConflictRetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunConflictRetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RetryTimeout) {
		toSerialize["retryTimeout"] = o.RetryTimeout
	}
	if !IsNil(o.InitialRetryDelay) {
		toSerialize["initialRetryDelay"] = o.InitialRetryDelay
	}
	if !IsNil(o.MaxRetryDelay) {
		toSerialize["maxRetryDelay"] = o.MaxRetryDelay
	}
	return toSerialize, nil
}

type NullableRunConflictRetry struct {
	value *RunConflictRetry
	isSet bool
}

func (v NullableRunConflictRetry) Get() *RunConflictRetry {
	return v.value
}

func (v *NullableRunConflictRetry) Set(val *RunConflictRetry) {
	v.value = val
	v.isSet = true
}

func (v NullableRunConflictRetry) IsSet() bool {
	return v.isSet
}

func (v *NullableRunConflictRetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunConflictRetry(val *RunConflictRetry) *NullableRunConflictRetry {
	return &NullableRunConflictRetry{value: val, isSet: true}
}

func (v NullableRunConflictRetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunConflictRetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
