/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CampaignOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignOperation{}

// CampaignOperation The operation the Campaign runs. Firmware is the only supported operation today.
type CampaignOperation struct {
	Firmware CampaignFirmwareOperation `json:"firmware"`
	// Excludes Racks materialized by prior Campaigns from this Campaign's candidate scope.
	ExcludeCampaignIds []string `json:"excludeCampaignIds,omitempty"`
}

type _CampaignOperation CampaignOperation

// NewCampaignOperation instantiates a new CampaignOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignOperation(firmware CampaignFirmwareOperation) *CampaignOperation {
	this := CampaignOperation{}
	this.Firmware = firmware
	return &this
}

// NewCampaignOperationWithDefaults instantiates a new CampaignOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignOperationWithDefaults() *CampaignOperation {
	this := CampaignOperation{}
	return &this
}

// GetFirmware returns the Firmware field value
func (o *CampaignOperation) GetFirmware() CampaignFirmwareOperation {
	if o == nil {
		var ret CampaignFirmwareOperation
		return ret
	}

	return o.Firmware
}

// GetFirmwareOk returns a tuple with the Firmware field value
// and a boolean to check if the value has been set.
func (o *CampaignOperation) GetFirmwareOk() (*CampaignFirmwareOperation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Firmware, true
}

// SetFirmware sets field value
func (o *CampaignOperation) SetFirmware(v CampaignFirmwareOperation) {
	o.Firmware = v
}

// GetExcludeCampaignIds returns the ExcludeCampaignIds field value if set, zero value otherwise.
func (o *CampaignOperation) GetExcludeCampaignIds() []string {
	if o == nil || IsNil(o.ExcludeCampaignIds) {
		var ret []string
		return ret
	}
	return o.ExcludeCampaignIds
}

// GetExcludeCampaignIdsOk returns a tuple with the ExcludeCampaignIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignOperation) GetExcludeCampaignIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeCampaignIds) {
		return nil, false
	}
	return o.ExcludeCampaignIds, true
}

// HasExcludeCampaignIds returns a boolean if a field has been set.
func (o *CampaignOperation) HasExcludeCampaignIds() bool {
	if o != nil && !IsNil(o.ExcludeCampaignIds) {
		return true
	}

	return false
}

// SetExcludeCampaignIds gets a reference to the given []string and assigns it to the ExcludeCampaignIds field.
func (o *CampaignOperation) SetExcludeCampaignIds(v []string) {
	o.ExcludeCampaignIds = v
}

func (o CampaignOperation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["firmware"] = o.Firmware
	if !IsNil(o.ExcludeCampaignIds) {
		toSerialize["excludeCampaignIds"] = o.ExcludeCampaignIds
	}
	return toSerialize, nil
}

func (o *CampaignOperation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"firmware",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCampaignOperation := _CampaignOperation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCampaignOperation)

	if err != nil {
		return err
	}

	*o = CampaignOperation(varCampaignOperation)

	return err
}

type NullableCampaignOperation struct {
	value *CampaignOperation
	isSet bool
}

func (v NullableCampaignOperation) Get() *CampaignOperation {
	return v.value
}

func (v *NullableCampaignOperation) Set(val *CampaignOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignOperation(val *CampaignOperation) *NullableCampaignOperation {
	return &NullableCampaignOperation{value: val, isSet: true}
}

func (v NullableCampaignOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
