// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AdvanceRunRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvanceRunRequest{}

// AdvanceRunRequest Request body for advancing a Run to its next phase.
type AdvanceRunRequest struct {
	// ID of the Site that owns the Run.
	SiteId string `json:"siteId"`
	// Optional guard: when set, the phase that would be opened must match this zero-based index, otherwise the advance is rejected.
	ExpectedPhaseIndex *int32 `json:"expectedPhaseIndex,omitempty"`
}

type _AdvanceRunRequest AdvanceRunRequest

// NewAdvanceRunRequest instantiates a new AdvanceRunRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvanceRunRequest(siteId string) *AdvanceRunRequest {
	this := AdvanceRunRequest{}
	this.SiteId = siteId
	return &this
}

// NewAdvanceRunRequestWithDefaults instantiates a new AdvanceRunRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvanceRunRequestWithDefaults() *AdvanceRunRequest {
	this := AdvanceRunRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *AdvanceRunRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *AdvanceRunRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *AdvanceRunRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetExpectedPhaseIndex returns the ExpectedPhaseIndex field value if set, zero value otherwise.
func (o *AdvanceRunRequest) GetExpectedPhaseIndex() int32 {
	if o == nil || IsNil(o.ExpectedPhaseIndex) {
		var ret int32
		return ret
	}
	return *o.ExpectedPhaseIndex
}

// GetExpectedPhaseIndexOk returns a tuple with the ExpectedPhaseIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvanceRunRequest) GetExpectedPhaseIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpectedPhaseIndex) {
		return nil, false
	}
	return o.ExpectedPhaseIndex, true
}

// HasExpectedPhaseIndex returns a boolean if a field has been set.
func (o *AdvanceRunRequest) HasExpectedPhaseIndex() bool {
	if o != nil && !IsNil(o.ExpectedPhaseIndex) {
		return true
	}

	return false
}

// SetExpectedPhaseIndex gets a reference to the given int32 and assigns it to the ExpectedPhaseIndex field.
func (o *AdvanceRunRequest) SetExpectedPhaseIndex(v int32) {
	o.ExpectedPhaseIndex = &v
}

func (o AdvanceRunRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvanceRunRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	if !IsNil(o.ExpectedPhaseIndex) {
		toSerialize["expectedPhaseIndex"] = o.ExpectedPhaseIndex
	}
	return toSerialize, nil
}

func (o *AdvanceRunRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdvanceRunRequest := _AdvanceRunRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdvanceRunRequest)

	if err != nil {
		return err
	}

	*o = AdvanceRunRequest(varAdvanceRunRequest)

	return err
}

type NullableAdvanceRunRequest struct {
	value *AdvanceRunRequest
	isSet bool
}

func (v NullableAdvanceRunRequest) Get() *AdvanceRunRequest {
	return v.value
}

func (v *NullableAdvanceRunRequest) Set(val *AdvanceRunRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvanceRunRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvanceRunRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvanceRunRequest(val *AdvanceRunRequest) *NullableAdvanceRunRequest {
	return &NullableAdvanceRunRequest{value: val, isSet: true}
}

func (v NullableAdvanceRunRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvanceRunRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
