// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the MeasurementTrustedProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeasurementTrustedProfile{}

// MeasurementTrustedProfile A measured-boot trusted system profile approval.
type MeasurementTrustedProfile struct {
	// Unique approval ID.
	ApprovalId string `json:"approvalId"`
	// ID of the measured-boot system profile.
	ProfileId string `json:"profileId"`
	// Whether the approval is consumed once or persists for future reports.
	ApprovalType string `json:"approvalType"`
	// Optional comma-separated PCR register selector.
	PcrRegisters *string `json:"pcrRegisters,omitempty"`
	// Optional operator comments about the approval.
	Comments *string `json:"comments,omitempty"`
	// Time when the approval was created.
	Created *time.Time `json:"created,omitempty"`
}

type _MeasurementTrustedProfile MeasurementTrustedProfile

// NewMeasurementTrustedProfile instantiates a new MeasurementTrustedProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeasurementTrustedProfile(approvalId string, profileId string, approvalType string) *MeasurementTrustedProfile {
	this := MeasurementTrustedProfile{}
	this.ApprovalId = approvalId
	this.ProfileId = profileId
	this.ApprovalType = approvalType
	return &this
}

// NewMeasurementTrustedProfileWithDefaults instantiates a new MeasurementTrustedProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeasurementTrustedProfileWithDefaults() *MeasurementTrustedProfile {
	this := MeasurementTrustedProfile{}
	return &this
}

// GetApprovalId returns the ApprovalId field value
func (o *MeasurementTrustedProfile) GetApprovalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApprovalId
}

// GetApprovalIdOk returns a tuple with the ApprovalId field value
// and a boolean to check if the value has been set.
func (o *MeasurementTrustedProfile) GetApprovalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApprovalId, true
}

// SetApprovalId sets field value
func (o *MeasurementTrustedProfile) SetApprovalId(v string) {
	o.ApprovalId = v
}

// GetProfileId returns the ProfileId field value
func (o *MeasurementTrustedProfile) GetProfileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProfileId
}

// GetProfileIdOk returns a tuple with the ProfileId field value
// and a boolean to check if the value has been set.
func (o *MeasurementTrustedProfile) GetProfileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfileId, true
}

// SetProfileId sets field value
func (o *MeasurementTrustedProfile) SetProfileId(v string) {
	o.ProfileId = v
}

// GetApprovalType returns the ApprovalType field value
func (o *MeasurementTrustedProfile) GetApprovalType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApprovalType
}

// GetApprovalTypeOk returns a tuple with the ApprovalType field value
// and a boolean to check if the value has been set.
func (o *MeasurementTrustedProfile) GetApprovalTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApprovalType, true
}

// SetApprovalType sets field value
func (o *MeasurementTrustedProfile) SetApprovalType(v string) {
	o.ApprovalType = v
}

// GetPcrRegisters returns the PcrRegisters field value if set, zero value otherwise.
func (o *MeasurementTrustedProfile) GetPcrRegisters() string {
	if o == nil || IsNil(o.PcrRegisters) {
		var ret string
		return ret
	}
	return *o.PcrRegisters
}

// GetPcrRegistersOk returns a tuple with the PcrRegisters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeasurementTrustedProfile) GetPcrRegistersOk() (*string, bool) {
	if o == nil || IsNil(o.PcrRegisters) {
		return nil, false
	}
	return o.PcrRegisters, true
}

// HasPcrRegisters returns a boolean if a field has been set.
func (o *MeasurementTrustedProfile) HasPcrRegisters() bool {
	if o != nil && !IsNil(o.PcrRegisters) {
		return true
	}

	return false
}

// SetPcrRegisters gets a reference to the given string and assigns it to the PcrRegisters field.
func (o *MeasurementTrustedProfile) SetPcrRegisters(v string) {
	o.PcrRegisters = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *MeasurementTrustedProfile) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeasurementTrustedProfile) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *MeasurementTrustedProfile) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *MeasurementTrustedProfile) SetComments(v string) {
	o.Comments = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *MeasurementTrustedProfile) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeasurementTrustedProfile) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *MeasurementTrustedProfile) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *MeasurementTrustedProfile) SetCreated(v time.Time) {
	o.Created = &v
}

func (o MeasurementTrustedProfile) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeasurementTrustedProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["approvalId"] = o.ApprovalId
	toSerialize["profileId"] = o.ProfileId
	toSerialize["approvalType"] = o.ApprovalType
	if !IsNil(o.PcrRegisters) {
		toSerialize["pcrRegisters"] = o.PcrRegisters
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	return toSerialize, nil
}

func (o *MeasurementTrustedProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"approvalId",
		"profileId",
		"approvalType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeasurementTrustedProfile := _MeasurementTrustedProfile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeasurementTrustedProfile)

	if err != nil {
		return err
	}

	*o = MeasurementTrustedProfile(varMeasurementTrustedProfile)

	return err
}

type NullableMeasurementTrustedProfile struct {
	value *MeasurementTrustedProfile
	isSet bool
}

func (v NullableMeasurementTrustedProfile) Get() *MeasurementTrustedProfile {
	return v.value
}

func (v *NullableMeasurementTrustedProfile) Set(val *MeasurementTrustedProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableMeasurementTrustedProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableMeasurementTrustedProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeasurementTrustedProfile(val *MeasurementTrustedProfile) *NullableMeasurementTrustedProfile {
	return &NullableMeasurementTrustedProfile{value: val, isSet: true}
}

func (v NullableMeasurementTrustedProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeasurementTrustedProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
