/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateCampaignRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCampaignRequest{}

// CreateCampaignRequest Request body for creating a Campaign. `operationType` is inferred from the operation and is not accepted here. Flow performs semantic validation (selector ranges, phase math, operation code membership) server-side.
type CreateCampaignRequest struct {
	// ID of the Site to create the Campaign on.
	SiteId string `json:"siteId"`
	// Human-readable name of the Campaign.
	Name string `json:"name"`
	// Optional free-form description.
	Description *string `json:"description,omitempty"`
	// Narrows the candidate Racks. Omit to target the full candidate scope (100%).
	Selector  *CampaignSelector `json:"selector,omitempty"`
	Options   CampaignOptions   `json:"options"`
	Operation CampaignOperation `json:"operation"`
}

type _CreateCampaignRequest CreateCampaignRequest

// NewCreateCampaignRequest instantiates a new CreateCampaignRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCampaignRequest(siteId string, name string, options CampaignOptions, operation CampaignOperation) *CreateCampaignRequest {
	this := CreateCampaignRequest{}
	this.SiteId = siteId
	this.Name = name
	this.Options = options
	this.Operation = operation
	return &this
}

// NewCreateCampaignRequestWithDefaults instantiates a new CreateCampaignRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCampaignRequestWithDefaults() *CreateCampaignRequest {
	this := CreateCampaignRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *CreateCampaignRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *CreateCampaignRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *CreateCampaignRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetName returns the Name field value
func (o *CreateCampaignRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateCampaignRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateCampaignRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateCampaignRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCampaignRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateCampaignRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateCampaignRequest) SetDescription(v string) {
	o.Description = &v
}

// GetSelector returns the Selector field value if set, zero value otherwise.
func (o *CreateCampaignRequest) GetSelector() CampaignSelector {
	if o == nil || IsNil(o.Selector) {
		var ret CampaignSelector
		return ret
	}
	return *o.Selector
}

// GetSelectorOk returns a tuple with the Selector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCampaignRequest) GetSelectorOk() (*CampaignSelector, bool) {
	if o == nil || IsNil(o.Selector) {
		return nil, false
	}
	return o.Selector, true
}

// HasSelector returns a boolean if a field has been set.
func (o *CreateCampaignRequest) HasSelector() bool {
	if o != nil && !IsNil(o.Selector) {
		return true
	}

	return false
}

// SetSelector gets a reference to the given CampaignSelector and assigns it to the Selector field.
func (o *CreateCampaignRequest) SetSelector(v CampaignSelector) {
	o.Selector = &v
}

// GetOptions returns the Options field value
func (o *CreateCampaignRequest) GetOptions() CampaignOptions {
	if o == nil {
		var ret CampaignOptions
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *CreateCampaignRequest) GetOptionsOk() (*CampaignOptions, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Options, true
}

// SetOptions sets field value
func (o *CreateCampaignRequest) SetOptions(v CampaignOptions) {
	o.Options = v
}

// GetOperation returns the Operation field value
func (o *CreateCampaignRequest) GetOperation() CampaignOperation {
	if o == nil {
		var ret CampaignOperation
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *CreateCampaignRequest) GetOperationOk() (*CampaignOperation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *CreateCampaignRequest) SetOperation(v CampaignOperation) {
	o.Operation = v
}

func (o CreateCampaignRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCampaignRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Selector) {
		toSerialize["selector"] = o.Selector
	}
	toSerialize["options"] = o.Options
	toSerialize["operation"] = o.Operation
	return toSerialize, nil
}

func (o *CreateCampaignRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"name",
		"options",
		"operation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCampaignRequest := _CreateCampaignRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCampaignRequest)

	if err != nil {
		return err
	}

	*o = CreateCampaignRequest(varCreateCampaignRequest)

	return err
}

type NullableCreateCampaignRequest struct {
	value *CreateCampaignRequest
	isSet bool
}

func (v NullableCreateCampaignRequest) Get() *CreateCampaignRequest {
	return v.value
}

func (v *NullableCreateCampaignRequest) Set(val *CreateCampaignRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCampaignRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCampaignRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCampaignRequest(val *CreateCampaignRequest) *NullableCreateCampaignRequest {
	return &NullableCreateCampaignRequest{value: val, isSet: true}
}

func (v NullableCreateCampaignRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCampaignRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
