/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the CampaignRandomOrdering type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignRandomOrdering{}

// CampaignRandomOrdering Orders targets randomly. `seed` is optional; Flow generates and stores one when omitted.
type CampaignRandomOrdering struct {
	// Optional seed for the deterministic random ordering.
	Seed *string `json:"seed,omitempty"`
}

// NewCampaignRandomOrdering instantiates a new CampaignRandomOrdering object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignRandomOrdering() *CampaignRandomOrdering {
	this := CampaignRandomOrdering{}
	return &this
}

// NewCampaignRandomOrderingWithDefaults instantiates a new CampaignRandomOrdering object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignRandomOrderingWithDefaults() *CampaignRandomOrdering {
	this := CampaignRandomOrdering{}
	return &this
}

// GetSeed returns the Seed field value if set, zero value otherwise.
func (o *CampaignRandomOrdering) GetSeed() string {
	if o == nil || IsNil(o.Seed) {
		var ret string
		return ret
	}
	return *o.Seed
}

// GetSeedOk returns a tuple with the Seed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignRandomOrdering) GetSeedOk() (*string, bool) {
	if o == nil || IsNil(o.Seed) {
		return nil, false
	}
	return o.Seed, true
}

// HasSeed returns a boolean if a field has been set.
func (o *CampaignRandomOrdering) HasSeed() bool {
	if o != nil && !IsNil(o.Seed) {
		return true
	}

	return false
}

// SetSeed gets a reference to the given string and assigns it to the Seed field.
func (o *CampaignRandomOrdering) SetSeed(v string) {
	o.Seed = &v
}

func (o CampaignRandomOrdering) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignRandomOrdering) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Seed) {
		toSerialize["seed"] = o.Seed
	}
	return toSerialize, nil
}

type NullableCampaignRandomOrdering struct {
	value *CampaignRandomOrdering
	isSet bool
}

func (v NullableCampaignRandomOrdering) Get() *CampaignRandomOrdering {
	return v.value
}

func (v *NullableCampaignRandomOrdering) Set(val *CampaignRandomOrdering) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignRandomOrdering) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignRandomOrdering) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignRandomOrdering(val *CampaignRandomOrdering) *NullableCampaignRandomOrdering {
	return &NullableCampaignRandomOrdering{value: val, isSet: true}
}

func (v NullableCampaignRandomOrdering) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignRandomOrdering) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
