// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InstanceSpectrumXAttachmentCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceSpectrumXAttachmentCreateRequest{}

// InstanceSpectrumXAttachmentCreateRequest Request data to attach a SpectrumX Partition to an Instance
type InstanceSpectrumXAttachmentCreateRequest struct {
	// ID of the SpectrumX Partition the attachment should associate with
	SpectrumXPartitionId string `json:"spectrumXPartitionId"`
	// Name of the SpectrumX device to use
	Device string `json:"device"`
	// Index of the device, used to identify which interface card to attach the Partition to
	DeviceInstance int32 `json:"deviceInstance"`
	// Type of SpectrumX attachment
	AttachmentType string `json:"attachmentType"`
	// Must be specified if attachmentType is Virtual
	VirtualFunctionId NullableInt32 `json:"virtualFunctionId,omitempty"`
}

type _InstanceSpectrumXAttachmentCreateRequest InstanceSpectrumXAttachmentCreateRequest

// NewInstanceSpectrumXAttachmentCreateRequest instantiates a new InstanceSpectrumXAttachmentCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceSpectrumXAttachmentCreateRequest(spectrumXPartitionId string, device string, deviceInstance int32, attachmentType string) *InstanceSpectrumXAttachmentCreateRequest {
	this := InstanceSpectrumXAttachmentCreateRequest{}
	this.SpectrumXPartitionId = spectrumXPartitionId
	this.Device = device
	this.DeviceInstance = deviceInstance
	this.AttachmentType = attachmentType
	return &this
}

// NewInstanceSpectrumXAttachmentCreateRequestWithDefaults instantiates a new InstanceSpectrumXAttachmentCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceSpectrumXAttachmentCreateRequestWithDefaults() *InstanceSpectrumXAttachmentCreateRequest {
	this := InstanceSpectrumXAttachmentCreateRequest{}
	return &this
}

// GetSpectrumXPartitionId returns the SpectrumXPartitionId field value
func (o *InstanceSpectrumXAttachmentCreateRequest) GetSpectrumXPartitionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpectrumXPartitionId
}

// GetSpectrumXPartitionIdOk returns a tuple with the SpectrumXPartitionId field value
// and a boolean to check if the value has been set.
func (o *InstanceSpectrumXAttachmentCreateRequest) GetSpectrumXPartitionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpectrumXPartitionId, true
}

// SetSpectrumXPartitionId sets field value
func (o *InstanceSpectrumXAttachmentCreateRequest) SetSpectrumXPartitionId(v string) {
	o.SpectrumXPartitionId = v
}

// GetDevice returns the Device field value
func (o *InstanceSpectrumXAttachmentCreateRequest) GetDevice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *InstanceSpectrumXAttachmentCreateRequest) GetDeviceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *InstanceSpectrumXAttachmentCreateRequest) SetDevice(v string) {
	o.Device = v
}

// GetDeviceInstance returns the DeviceInstance field value
func (o *InstanceSpectrumXAttachmentCreateRequest) GetDeviceInstance() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DeviceInstance
}

// GetDeviceInstanceOk returns a tuple with the DeviceInstance field value
// and a boolean to check if the value has been set.
func (o *InstanceSpectrumXAttachmentCreateRequest) GetDeviceInstanceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceInstance, true
}

// SetDeviceInstance sets field value
func (o *InstanceSpectrumXAttachmentCreateRequest) SetDeviceInstance(v int32) {
	o.DeviceInstance = v
}

// GetAttachmentType returns the AttachmentType field value
func (o *InstanceSpectrumXAttachmentCreateRequest) GetAttachmentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttachmentType
}

// GetAttachmentTypeOk returns a tuple with the AttachmentType field value
// and a boolean to check if the value has been set.
func (o *InstanceSpectrumXAttachmentCreateRequest) GetAttachmentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttachmentType, true
}

// SetAttachmentType sets field value
func (o *InstanceSpectrumXAttachmentCreateRequest) SetAttachmentType(v string) {
	o.AttachmentType = v
}

// GetVirtualFunctionId returns the VirtualFunctionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceSpectrumXAttachmentCreateRequest) GetVirtualFunctionId() int32 {
	if o == nil || IsNil(o.VirtualFunctionId.Get()) {
		var ret int32
		return ret
	}
	return *o.VirtualFunctionId.Get()
}

// GetVirtualFunctionIdOk returns a tuple with the VirtualFunctionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceSpectrumXAttachmentCreateRequest) GetVirtualFunctionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VirtualFunctionId.Get(), o.VirtualFunctionId.IsSet()
}

// HasVirtualFunctionId returns a boolean if a field has been set.
func (o *InstanceSpectrumXAttachmentCreateRequest) HasVirtualFunctionId() bool {
	if o != nil && o.VirtualFunctionId.IsSet() {
		return true
	}

	return false
}

// SetVirtualFunctionId gets a reference to the given NullableInt32 and assigns it to the VirtualFunctionId field.
func (o *InstanceSpectrumXAttachmentCreateRequest) SetVirtualFunctionId(v int32) {
	o.VirtualFunctionId.Set(&v)
}

// SetVirtualFunctionIdNil sets the value for VirtualFunctionId to be an explicit nil
func (o *InstanceSpectrumXAttachmentCreateRequest) SetVirtualFunctionIdNil() {
	o.VirtualFunctionId.Set(nil)
}

// UnsetVirtualFunctionId ensures that no value is present for VirtualFunctionId, not even an explicit nil
func (o *InstanceSpectrumXAttachmentCreateRequest) UnsetVirtualFunctionId() {
	o.VirtualFunctionId.Unset()
}

func (o InstanceSpectrumXAttachmentCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceSpectrumXAttachmentCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["spectrumXPartitionId"] = o.SpectrumXPartitionId
	toSerialize["device"] = o.Device
	toSerialize["deviceInstance"] = o.DeviceInstance
	toSerialize["attachmentType"] = o.AttachmentType
	if o.VirtualFunctionId.IsSet() {
		toSerialize["virtualFunctionId"] = o.VirtualFunctionId.Get()
	}
	return toSerialize, nil
}

func (o *InstanceSpectrumXAttachmentCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spectrumXPartitionId",
		"device",
		"deviceInstance",
		"attachmentType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceSpectrumXAttachmentCreateRequest := _InstanceSpectrumXAttachmentCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varInstanceSpectrumXAttachmentCreateRequest)

	if err != nil {
		return err
	}

	*o = InstanceSpectrumXAttachmentCreateRequest(varInstanceSpectrumXAttachmentCreateRequest)

	return err
}

type NullableInstanceSpectrumXAttachmentCreateRequest struct {
	value *InstanceSpectrumXAttachmentCreateRequest
	isSet bool
}

func (v NullableInstanceSpectrumXAttachmentCreateRequest) Get() *InstanceSpectrumXAttachmentCreateRequest {
	return v.value
}

func (v *NullableInstanceSpectrumXAttachmentCreateRequest) Set(val *InstanceSpectrumXAttachmentCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceSpectrumXAttachmentCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceSpectrumXAttachmentCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceSpectrumXAttachmentCreateRequest(val *InstanceSpectrumXAttachmentCreateRequest) *NullableInstanceSpectrumXAttachmentCreateRequest {
	return &NullableInstanceSpectrumXAttachmentCreateRequest{value: val, isSet: true}
}

func (v NullableInstanceSpectrumXAttachmentCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceSpectrumXAttachmentCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
