/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the CampaignSafetyGate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignSafetyGate{}

// CampaignSafetyGate Exactly one of `failureRate` or `failureCount` must be set.
type CampaignSafetyGate struct {
	FailureRate  *CampaignFailureRateGate  `json:"failureRate,omitempty"`
	FailureCount *CampaignFailureCountGate `json:"failureCount,omitempty"`
}

// NewCampaignSafetyGate instantiates a new CampaignSafetyGate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignSafetyGate() *CampaignSafetyGate {
	this := CampaignSafetyGate{}
	return &this
}

// NewCampaignSafetyGateWithDefaults instantiates a new CampaignSafetyGate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignSafetyGateWithDefaults() *CampaignSafetyGate {
	this := CampaignSafetyGate{}
	return &this
}

// GetFailureRate returns the FailureRate field value if set, zero value otherwise.
func (o *CampaignSafetyGate) GetFailureRate() CampaignFailureRateGate {
	if o == nil || IsNil(o.FailureRate) {
		var ret CampaignFailureRateGate
		return ret
	}
	return *o.FailureRate
}

// GetFailureRateOk returns a tuple with the FailureRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignSafetyGate) GetFailureRateOk() (*CampaignFailureRateGate, bool) {
	if o == nil || IsNil(o.FailureRate) {
		return nil, false
	}
	return o.FailureRate, true
}

// HasFailureRate returns a boolean if a field has been set.
func (o *CampaignSafetyGate) HasFailureRate() bool {
	if o != nil && !IsNil(o.FailureRate) {
		return true
	}

	return false
}

// SetFailureRate gets a reference to the given CampaignFailureRateGate and assigns it to the FailureRate field.
func (o *CampaignSafetyGate) SetFailureRate(v CampaignFailureRateGate) {
	o.FailureRate = &v
}

// GetFailureCount returns the FailureCount field value if set, zero value otherwise.
func (o *CampaignSafetyGate) GetFailureCount() CampaignFailureCountGate {
	if o == nil || IsNil(o.FailureCount) {
		var ret CampaignFailureCountGate
		return ret
	}
	return *o.FailureCount
}

// GetFailureCountOk returns a tuple with the FailureCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignSafetyGate) GetFailureCountOk() (*CampaignFailureCountGate, bool) {
	if o == nil || IsNil(o.FailureCount) {
		return nil, false
	}
	return o.FailureCount, true
}

// HasFailureCount returns a boolean if a field has been set.
func (o *CampaignSafetyGate) HasFailureCount() bool {
	if o != nil && !IsNil(o.FailureCount) {
		return true
	}

	return false
}

// SetFailureCount gets a reference to the given CampaignFailureCountGate and assigns it to the FailureCount field.
func (o *CampaignSafetyGate) SetFailureCount(v CampaignFailureCountGate) {
	o.FailureCount = &v
}

func (o CampaignSafetyGate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignSafetyGate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FailureRate) {
		toSerialize["failureRate"] = o.FailureRate
	}
	if !IsNil(o.FailureCount) {
		toSerialize["failureCount"] = o.FailureCount
	}
	return toSerialize, nil
}

type NullableCampaignSafetyGate struct {
	value *CampaignSafetyGate
	isSet bool
}

func (v NullableCampaignSafetyGate) Get() *CampaignSafetyGate {
	return v.value
}

func (v *NullableCampaignSafetyGate) Set(val *CampaignSafetyGate) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignSafetyGate) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignSafetyGate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignSafetyGate(val *CampaignSafetyGate) *NullableCampaignSafetyGate {
	return &NullableCampaignSafetyGate{value: val, isSet: true}
}

func (v NullableCampaignSafetyGate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignSafetyGate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
