// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the MeasuredBootTrustedMachine type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeasuredBootTrustedMachine{}

// MeasuredBootTrustedMachine A measured-boot trusted Machine approval.
type MeasuredBootTrustedMachine struct {
	// Unique approval ID.
	ApprovalId string `json:"approvalId"`
	// Machine UUID, or `*` when the approval applies to all Machines.
	MachineId string `json:"machineId"`
	// Whether the approval is consumed once or persists for future reports.
	ApprovalType string `json:"approvalType"`
	// Optional comma-separated PCR register selector.
	PcrRegisters *string `json:"pcrRegisters,omitempty"`
	// Optional operator comments about the approval.
	Comments *string `json:"comments,omitempty"`
	// Time when the approval was created.
	Created *time.Time `json:"created,omitempty"`
}

type _MeasuredBootTrustedMachine MeasuredBootTrustedMachine

// NewMeasuredBootTrustedMachine instantiates a new MeasuredBootTrustedMachine object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeasuredBootTrustedMachine(approvalId string, machineId string, approvalType string) *MeasuredBootTrustedMachine {
	this := MeasuredBootTrustedMachine{}
	this.ApprovalId = approvalId
	this.MachineId = machineId
	this.ApprovalType = approvalType
	return &this
}

// NewMeasuredBootTrustedMachineWithDefaults instantiates a new MeasuredBootTrustedMachine object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeasuredBootTrustedMachineWithDefaults() *MeasuredBootTrustedMachine {
	this := MeasuredBootTrustedMachine{}
	return &this
}

// GetApprovalId returns the ApprovalId field value
func (o *MeasuredBootTrustedMachine) GetApprovalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApprovalId
}

// GetApprovalIdOk returns a tuple with the ApprovalId field value
// and a boolean to check if the value has been set.
func (o *MeasuredBootTrustedMachine) GetApprovalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApprovalId, true
}

// SetApprovalId sets field value
func (o *MeasuredBootTrustedMachine) SetApprovalId(v string) {
	o.ApprovalId = v
}

// GetMachineId returns the MachineId field value
func (o *MeasuredBootTrustedMachine) GetMachineId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MachineId
}

// GetMachineIdOk returns a tuple with the MachineId field value
// and a boolean to check if the value has been set.
func (o *MeasuredBootTrustedMachine) GetMachineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MachineId, true
}

// SetMachineId sets field value
func (o *MeasuredBootTrustedMachine) SetMachineId(v string) {
	o.MachineId = v
}

// GetApprovalType returns the ApprovalType field value
func (o *MeasuredBootTrustedMachine) GetApprovalType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApprovalType
}

// GetApprovalTypeOk returns a tuple with the ApprovalType field value
// and a boolean to check if the value has been set.
func (o *MeasuredBootTrustedMachine) GetApprovalTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApprovalType, true
}

// SetApprovalType sets field value
func (o *MeasuredBootTrustedMachine) SetApprovalType(v string) {
	o.ApprovalType = v
}

// GetPcrRegisters returns the PcrRegisters field value if set, zero value otherwise.
func (o *MeasuredBootTrustedMachine) GetPcrRegisters() string {
	if o == nil || IsNil(o.PcrRegisters) {
		var ret string
		return ret
	}
	return *o.PcrRegisters
}

// GetPcrRegistersOk returns a tuple with the PcrRegisters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeasuredBootTrustedMachine) GetPcrRegistersOk() (*string, bool) {
	if o == nil || IsNil(o.PcrRegisters) {
		return nil, false
	}
	return o.PcrRegisters, true
}

// HasPcrRegisters returns a boolean if a field has been set.
func (o *MeasuredBootTrustedMachine) HasPcrRegisters() bool {
	if o != nil && !IsNil(o.PcrRegisters) {
		return true
	}

	return false
}

// SetPcrRegisters gets a reference to the given string and assigns it to the PcrRegisters field.
func (o *MeasuredBootTrustedMachine) SetPcrRegisters(v string) {
	o.PcrRegisters = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *MeasuredBootTrustedMachine) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeasuredBootTrustedMachine) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *MeasuredBootTrustedMachine) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *MeasuredBootTrustedMachine) SetComments(v string) {
	o.Comments = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *MeasuredBootTrustedMachine) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeasuredBootTrustedMachine) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *MeasuredBootTrustedMachine) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *MeasuredBootTrustedMachine) SetCreated(v time.Time) {
	o.Created = &v
}

func (o MeasuredBootTrustedMachine) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeasuredBootTrustedMachine) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["approvalId"] = o.ApprovalId
	toSerialize["machineId"] = o.MachineId
	toSerialize["approvalType"] = o.ApprovalType
	if !IsNil(o.PcrRegisters) {
		toSerialize["pcrRegisters"] = o.PcrRegisters
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	return toSerialize, nil
}

func (o *MeasuredBootTrustedMachine) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"approvalId",
		"machineId",
		"approvalType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeasuredBootTrustedMachine := _MeasuredBootTrustedMachine{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeasuredBootTrustedMachine)

	if err != nil {
		return err
	}

	*o = MeasuredBootTrustedMachine(varMeasuredBootTrustedMachine)

	return err
}

type NullableMeasuredBootTrustedMachine struct {
	value *MeasuredBootTrustedMachine
	isSet bool
}

func (v NullableMeasuredBootTrustedMachine) Get() *MeasuredBootTrustedMachine {
	return v.value
}

func (v *NullableMeasuredBootTrustedMachine) Set(val *MeasuredBootTrustedMachine) {
	v.value = val
	v.isSet = true
}

func (v NullableMeasuredBootTrustedMachine) IsSet() bool {
	return v.isSet
}

func (v *NullableMeasuredBootTrustedMachine) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeasuredBootTrustedMachine(val *MeasuredBootTrustedMachine) *NullableMeasuredBootTrustedMachine {
	return &NullableMeasuredBootTrustedMachine{value: val, isSet: true}
}

func (v NullableMeasuredBootTrustedMachine) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeasuredBootTrustedMachine) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
