/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the CampaignPhasePolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignPhasePolicy{}

// CampaignPhasePolicy Divides the selected targets into phases. Set at most one of `equal`, `percentage`, or `count`; omit the whole policy for a single phase covering all targets.
type CampaignPhasePolicy struct {
	Equal      *CampaignEqualPhases      `json:"equal,omitempty"`
	Percentage *CampaignPercentagePhases `json:"percentage,omitempty"`
	Count      *CampaignCountPhases      `json:"count,omitempty"`
	// When true, phases advance automatically as long as safety gates are not tripped. When false (default) each completed phase pauses at a phase gate until advanced explicitly.
	AutoAdvance *bool `json:"autoAdvance,omitempty"`
}

// NewCampaignPhasePolicy instantiates a new CampaignPhasePolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignPhasePolicy() *CampaignPhasePolicy {
	this := CampaignPhasePolicy{}
	var autoAdvance bool = false
	this.AutoAdvance = &autoAdvance
	return &this
}

// NewCampaignPhasePolicyWithDefaults instantiates a new CampaignPhasePolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignPhasePolicyWithDefaults() *CampaignPhasePolicy {
	this := CampaignPhasePolicy{}
	var autoAdvance bool = false
	this.AutoAdvance = &autoAdvance
	return &this
}

// GetEqual returns the Equal field value if set, zero value otherwise.
func (o *CampaignPhasePolicy) GetEqual() CampaignEqualPhases {
	if o == nil || IsNil(o.Equal) {
		var ret CampaignEqualPhases
		return ret
	}
	return *o.Equal
}

// GetEqualOk returns a tuple with the Equal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPhasePolicy) GetEqualOk() (*CampaignEqualPhases, bool) {
	if o == nil || IsNil(o.Equal) {
		return nil, false
	}
	return o.Equal, true
}

// HasEqual returns a boolean if a field has been set.
func (o *CampaignPhasePolicy) HasEqual() bool {
	if o != nil && !IsNil(o.Equal) {
		return true
	}

	return false
}

// SetEqual gets a reference to the given CampaignEqualPhases and assigns it to the Equal field.
func (o *CampaignPhasePolicy) SetEqual(v CampaignEqualPhases) {
	o.Equal = &v
}

// GetPercentage returns the Percentage field value if set, zero value otherwise.
func (o *CampaignPhasePolicy) GetPercentage() CampaignPercentagePhases {
	if o == nil || IsNil(o.Percentage) {
		var ret CampaignPercentagePhases
		return ret
	}
	return *o.Percentage
}

// GetPercentageOk returns a tuple with the Percentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPhasePolicy) GetPercentageOk() (*CampaignPercentagePhases, bool) {
	if o == nil || IsNil(o.Percentage) {
		return nil, false
	}
	return o.Percentage, true
}

// HasPercentage returns a boolean if a field has been set.
func (o *CampaignPhasePolicy) HasPercentage() bool {
	if o != nil && !IsNil(o.Percentage) {
		return true
	}

	return false
}

// SetPercentage gets a reference to the given CampaignPercentagePhases and assigns it to the Percentage field.
func (o *CampaignPhasePolicy) SetPercentage(v CampaignPercentagePhases) {
	o.Percentage = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *CampaignPhasePolicy) GetCount() CampaignCountPhases {
	if o == nil || IsNil(o.Count) {
		var ret CampaignCountPhases
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPhasePolicy) GetCountOk() (*CampaignCountPhases, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *CampaignPhasePolicy) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given CampaignCountPhases and assigns it to the Count field.
func (o *CampaignPhasePolicy) SetCount(v CampaignCountPhases) {
	o.Count = &v
}

// GetAutoAdvance returns the AutoAdvance field value if set, zero value otherwise.
func (o *CampaignPhasePolicy) GetAutoAdvance() bool {
	if o == nil || IsNil(o.AutoAdvance) {
		var ret bool
		return ret
	}
	return *o.AutoAdvance
}

// GetAutoAdvanceOk returns a tuple with the AutoAdvance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPhasePolicy) GetAutoAdvanceOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoAdvance) {
		return nil, false
	}
	return o.AutoAdvance, true
}

// HasAutoAdvance returns a boolean if a field has been set.
func (o *CampaignPhasePolicy) HasAutoAdvance() bool {
	if o != nil && !IsNil(o.AutoAdvance) {
		return true
	}

	return false
}

// SetAutoAdvance gets a reference to the given bool and assigns it to the AutoAdvance field.
func (o *CampaignPhasePolicy) SetAutoAdvance(v bool) {
	o.AutoAdvance = &v
}

func (o CampaignPhasePolicy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignPhasePolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Equal) {
		toSerialize["equal"] = o.Equal
	}
	if !IsNil(o.Percentage) {
		toSerialize["percentage"] = o.Percentage
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.AutoAdvance) {
		toSerialize["autoAdvance"] = o.AutoAdvance
	}
	return toSerialize, nil
}

type NullableCampaignPhasePolicy struct {
	value *CampaignPhasePolicy
	isSet bool
}

func (v NullableCampaignPhasePolicy) Get() *CampaignPhasePolicy {
	return v.value
}

func (v *NullableCampaignPhasePolicy) Set(val *CampaignPhasePolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignPhasePolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignPhasePolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignPhasePolicy(val *CampaignPhasePolicy) *NullableCampaignPhasePolicy {
	return &NullableCampaignPhasePolicy{value: val, isSet: true}
}

func (v NullableCampaignPhasePolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignPhasePolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
