/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the CampaignConflictRetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignConflictRetry{}

// CampaignConflictRetry Retry backoff for blocked targets. Durations are Go duration strings (e.g. `30m`, `10s`); an empty value means \"use the operation default\".
type CampaignConflictRetry struct {
	// Total time to keep retrying a blocked target before giving up.
	RetryTimeout *string `json:"retryTimeout,omitempty"`
	// Delay before the first retry.
	InitialRetryDelay *string `json:"initialRetryDelay,omitempty"`
	// Cap on the exponentially growing retry delay.
	MaxRetryDelay *string `json:"maxRetryDelay,omitempty"`
}

// NewCampaignConflictRetry instantiates a new CampaignConflictRetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignConflictRetry() *CampaignConflictRetry {
	this := CampaignConflictRetry{}
	return &this
}

// NewCampaignConflictRetryWithDefaults instantiates a new CampaignConflictRetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignConflictRetryWithDefaults() *CampaignConflictRetry {
	this := CampaignConflictRetry{}
	return &this
}

// GetRetryTimeout returns the RetryTimeout field value if set, zero value otherwise.
func (o *CampaignConflictRetry) GetRetryTimeout() string {
	if o == nil || IsNil(o.RetryTimeout) {
		var ret string
		return ret
	}
	return *o.RetryTimeout
}

// GetRetryTimeoutOk returns a tuple with the RetryTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignConflictRetry) GetRetryTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.RetryTimeout) {
		return nil, false
	}
	return o.RetryTimeout, true
}

// HasRetryTimeout returns a boolean if a field has been set.
func (o *CampaignConflictRetry) HasRetryTimeout() bool {
	if o != nil && !IsNil(o.RetryTimeout) {
		return true
	}

	return false
}

// SetRetryTimeout gets a reference to the given string and assigns it to the RetryTimeout field.
func (o *CampaignConflictRetry) SetRetryTimeout(v string) {
	o.RetryTimeout = &v
}

// GetInitialRetryDelay returns the InitialRetryDelay field value if set, zero value otherwise.
func (o *CampaignConflictRetry) GetInitialRetryDelay() string {
	if o == nil || IsNil(o.InitialRetryDelay) {
		var ret string
		return ret
	}
	return *o.InitialRetryDelay
}

// GetInitialRetryDelayOk returns a tuple with the InitialRetryDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignConflictRetry) GetInitialRetryDelayOk() (*string, bool) {
	if o == nil || IsNil(o.InitialRetryDelay) {
		return nil, false
	}
	return o.InitialRetryDelay, true
}

// HasInitialRetryDelay returns a boolean if a field has been set.
func (o *CampaignConflictRetry) HasInitialRetryDelay() bool {
	if o != nil && !IsNil(o.InitialRetryDelay) {
		return true
	}

	return false
}

// SetInitialRetryDelay gets a reference to the given string and assigns it to the InitialRetryDelay field.
func (o *CampaignConflictRetry) SetInitialRetryDelay(v string) {
	o.InitialRetryDelay = &v
}

// GetMaxRetryDelay returns the MaxRetryDelay field value if set, zero value otherwise.
func (o *CampaignConflictRetry) GetMaxRetryDelay() string {
	if o == nil || IsNil(o.MaxRetryDelay) {
		var ret string
		return ret
	}
	return *o.MaxRetryDelay
}

// GetMaxRetryDelayOk returns a tuple with the MaxRetryDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignConflictRetry) GetMaxRetryDelayOk() (*string, bool) {
	if o == nil || IsNil(o.MaxRetryDelay) {
		return nil, false
	}
	return o.MaxRetryDelay, true
}

// HasMaxRetryDelay returns a boolean if a field has been set.
func (o *CampaignConflictRetry) HasMaxRetryDelay() bool {
	if o != nil && !IsNil(o.MaxRetryDelay) {
		return true
	}

	return false
}

// SetMaxRetryDelay gets a reference to the given string and assigns it to the MaxRetryDelay field.
func (o *CampaignConflictRetry) SetMaxRetryDelay(v string) {
	o.MaxRetryDelay = &v
}

func (o CampaignConflictRetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignConflictRetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RetryTimeout) {
		toSerialize["retryTimeout"] = o.RetryTimeout
	}
	if !IsNil(o.InitialRetryDelay) {
		toSerialize["initialRetryDelay"] = o.InitialRetryDelay
	}
	if !IsNil(o.MaxRetryDelay) {
		toSerialize["maxRetryDelay"] = o.MaxRetryDelay
	}
	return toSerialize, nil
}

type NullableCampaignConflictRetry struct {
	value *CampaignConflictRetry
	isSet bool
}

func (v NullableCampaignConflictRetry) Get() *CampaignConflictRetry {
	return v.value
}

func (v *NullableCampaignConflictRetry) Set(val *CampaignConflictRetry) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignConflictRetry) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignConflictRetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignConflictRetry(val *CampaignConflictRetry) *NullableCampaignConflictRetry {
	return &NullableCampaignConflictRetry{value: val, isSet: true}
}

func (v NullableCampaignConflictRetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignConflictRetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
