/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the RunPhasePolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunPhasePolicy{}

// RunPhasePolicy Divides the selected targets into phases. Set at most one of `equal`, `percentage`, or `count`; omit the whole policy for a single phase covering all targets.
type RunPhasePolicy struct {
	Equal      *RunEqualPhases      `json:"equal,omitempty"`
	Percentage *RunPercentagePhases `json:"percentage,omitempty"`
	Count      *RunCountPhases      `json:"count,omitempty"`
	// When true, phases advance automatically as long as safety gates are not tripped. When false (default) each completed phase pauses at a phase gate until advanced explicitly.
	AutoAdvance *bool `json:"autoAdvance,omitempty"`
}

// NewRunPhasePolicy instantiates a new RunPhasePolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunPhasePolicy() *RunPhasePolicy {
	this := RunPhasePolicy{}
	var autoAdvance bool = false
	this.AutoAdvance = &autoAdvance
	return &this
}

// NewRunPhasePolicyWithDefaults instantiates a new RunPhasePolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunPhasePolicyWithDefaults() *RunPhasePolicy {
	this := RunPhasePolicy{}
	var autoAdvance bool = false
	this.AutoAdvance = &autoAdvance
	return &this
}

// GetEqual returns the Equal field value if set, zero value otherwise.
func (o *RunPhasePolicy) GetEqual() RunEqualPhases {
	if o == nil || IsNil(o.Equal) {
		var ret RunEqualPhases
		return ret
	}
	return *o.Equal
}

// GetEqualOk returns a tuple with the Equal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunPhasePolicy) GetEqualOk() (*RunEqualPhases, bool) {
	if o == nil || IsNil(o.Equal) {
		return nil, false
	}
	return o.Equal, true
}

// HasEqual returns a boolean if a field has been set.
func (o *RunPhasePolicy) HasEqual() bool {
	if o != nil && !IsNil(o.Equal) {
		return true
	}

	return false
}

// SetEqual gets a reference to the given RunEqualPhases and assigns it to the Equal field.
func (o *RunPhasePolicy) SetEqual(v RunEqualPhases) {
	o.Equal = &v
}

// GetPercentage returns the Percentage field value if set, zero value otherwise.
func (o *RunPhasePolicy) GetPercentage() RunPercentagePhases {
	if o == nil || IsNil(o.Percentage) {
		var ret RunPercentagePhases
		return ret
	}
	return *o.Percentage
}

// GetPercentageOk returns a tuple with the Percentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunPhasePolicy) GetPercentageOk() (*RunPercentagePhases, bool) {
	if o == nil || IsNil(o.Percentage) {
		return nil, false
	}
	return o.Percentage, true
}

// HasPercentage returns a boolean if a field has been set.
func (o *RunPhasePolicy) HasPercentage() bool {
	if o != nil && !IsNil(o.Percentage) {
		return true
	}

	return false
}

// SetPercentage gets a reference to the given RunPercentagePhases and assigns it to the Percentage field.
func (o *RunPhasePolicy) SetPercentage(v RunPercentagePhases) {
	o.Percentage = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *RunPhasePolicy) GetCount() RunCountPhases {
	if o == nil || IsNil(o.Count) {
		var ret RunCountPhases
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunPhasePolicy) GetCountOk() (*RunCountPhases, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *RunPhasePolicy) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given RunCountPhases and assigns it to the Count field.
func (o *RunPhasePolicy) SetCount(v RunCountPhases) {
	o.Count = &v
}

// GetAutoAdvance returns the AutoAdvance field value if set, zero value otherwise.
func (o *RunPhasePolicy) GetAutoAdvance() bool {
	if o == nil || IsNil(o.AutoAdvance) {
		var ret bool
		return ret
	}
	return *o.AutoAdvance
}

// GetAutoAdvanceOk returns a tuple with the AutoAdvance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunPhasePolicy) GetAutoAdvanceOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoAdvance) {
		return nil, false
	}
	return o.AutoAdvance, true
}

// HasAutoAdvance returns a boolean if a field has been set.
func (o *RunPhasePolicy) HasAutoAdvance() bool {
	if o != nil && !IsNil(o.AutoAdvance) {
		return true
	}

	return false
}

// SetAutoAdvance gets a reference to the given bool and assigns it to the AutoAdvance field.
func (o *RunPhasePolicy) SetAutoAdvance(v bool) {
	o.AutoAdvance = &v
}

func (o RunPhasePolicy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunPhasePolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Equal) {
		toSerialize["equal"] = o.Equal
	}
	if !IsNil(o.Percentage) {
		toSerialize["percentage"] = o.Percentage
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.AutoAdvance) {
		toSerialize["autoAdvance"] = o.AutoAdvance
	}
	return toSerialize, nil
}

type NullableRunPhasePolicy struct {
	value *RunPhasePolicy
	isSet bool
}

func (v NullableRunPhasePolicy) Get() *RunPhasePolicy {
	return v.value
}

func (v *NullableRunPhasePolicy) Set(val *RunPhasePolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableRunPhasePolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableRunPhasePolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunPhasePolicy(val *RunPhasePolicy) *NullableRunPhasePolicy {
	return &NullableRunPhasePolicy{value: val, isSet: true}
}

func (v NullableRunPhasePolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunPhasePolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
