/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RunOutcomeCounts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunOutcomeCounts{}

// RunOutcomeCounts Counts terminal target outcomes within a phase scope.
type RunOutcomeCounts struct {
	// Targets that completed successfully.
	Completed int32 `json:"completed"`
	// Targets that failed.
	Failed int32 `json:"failed"`
	// Targets that were terminated (e.g. by cancellation).
	Terminated int32 `json:"terminated"`
	// Targets that were skipped.
	Skipped int32 `json:"skipped"`
}

type _RunOutcomeCounts RunOutcomeCounts

// NewRunOutcomeCounts instantiates a new RunOutcomeCounts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunOutcomeCounts(completed int32, failed int32, terminated int32, skipped int32) *RunOutcomeCounts {
	this := RunOutcomeCounts{}
	this.Completed = completed
	this.Failed = failed
	this.Terminated = terminated
	this.Skipped = skipped
	return &this
}

// NewRunOutcomeCountsWithDefaults instantiates a new RunOutcomeCounts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunOutcomeCountsWithDefaults() *RunOutcomeCounts {
	this := RunOutcomeCounts{}
	return &this
}

// GetCompleted returns the Completed field value
func (o *RunOutcomeCounts) GetCompleted() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Completed
}

// GetCompletedOk returns a tuple with the Completed field value
// and a boolean to check if the value has been set.
func (o *RunOutcomeCounts) GetCompletedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Completed, true
}

// SetCompleted sets field value
func (o *RunOutcomeCounts) SetCompleted(v int32) {
	o.Completed = v
}

// GetFailed returns the Failed field value
func (o *RunOutcomeCounts) GetFailed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Failed
}

// GetFailedOk returns a tuple with the Failed field value
// and a boolean to check if the value has been set.
func (o *RunOutcomeCounts) GetFailedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Failed, true
}

// SetFailed sets field value
func (o *RunOutcomeCounts) SetFailed(v int32) {
	o.Failed = v
}

// GetTerminated returns the Terminated field value
func (o *RunOutcomeCounts) GetTerminated() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Terminated
}

// GetTerminatedOk returns a tuple with the Terminated field value
// and a boolean to check if the value has been set.
func (o *RunOutcomeCounts) GetTerminatedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Terminated, true
}

// SetTerminated sets field value
func (o *RunOutcomeCounts) SetTerminated(v int32) {
	o.Terminated = v
}

// GetSkipped returns the Skipped field value
func (o *RunOutcomeCounts) GetSkipped() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Skipped
}

// GetSkippedOk returns a tuple with the Skipped field value
// and a boolean to check if the value has been set.
func (o *RunOutcomeCounts) GetSkippedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Skipped, true
}

// SetSkipped sets field value
func (o *RunOutcomeCounts) SetSkipped(v int32) {
	o.Skipped = v
}

func (o RunOutcomeCounts) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunOutcomeCounts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["completed"] = o.Completed
	toSerialize["failed"] = o.Failed
	toSerialize["terminated"] = o.Terminated
	toSerialize["skipped"] = o.Skipped
	return toSerialize, nil
}

func (o *RunOutcomeCounts) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"completed",
		"failed",
		"terminated",
		"skipped",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRunOutcomeCounts := _RunOutcomeCounts{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRunOutcomeCounts)

	if err != nil {
		return err
	}

	*o = RunOutcomeCounts(varRunOutcomeCounts)

	return err
}

type NullableRunOutcomeCounts struct {
	value *RunOutcomeCounts
	isSet bool
}

func (v NullableRunOutcomeCounts) Get() *RunOutcomeCounts {
	return v.value
}

func (v *NullableRunOutcomeCounts) Set(val *RunOutcomeCounts) {
	v.value = val
	v.isSet = true
}

func (v NullableRunOutcomeCounts) IsSet() bool {
	return v.isSet
}

func (v *NullableRunOutcomeCounts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunOutcomeCounts(val *RunOutcomeCounts) *NullableRunOutcomeCounts {
	return &NullableRunOutcomeCounts{value: val, isSet: true}
}

func (v NullableRunOutcomeCounts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunOutcomeCounts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
