/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CancelCampaignRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelCampaignRequest{}

// CancelCampaignRequest Request body for cancelling a Campaign.
type CancelCampaignRequest struct {
	// ID of the Site that owns the Campaign.
	SiteId string `json:"siteId"`
	// Optional free-form reason recorded with the cancellation.
	Reason *string `json:"reason,omitempty"`
}

type _CancelCampaignRequest CancelCampaignRequest

// NewCancelCampaignRequest instantiates a new CancelCampaignRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelCampaignRequest(siteId string) *CancelCampaignRequest {
	this := CancelCampaignRequest{}
	this.SiteId = siteId
	return &this
}

// NewCancelCampaignRequestWithDefaults instantiates a new CancelCampaignRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelCampaignRequestWithDefaults() *CancelCampaignRequest {
	this := CancelCampaignRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *CancelCampaignRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *CancelCampaignRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *CancelCampaignRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *CancelCampaignRequest) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelCampaignRequest) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *CancelCampaignRequest) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *CancelCampaignRequest) SetReason(v string) {
	o.Reason = &v
}

func (o CancelCampaignRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelCampaignRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

func (o *CancelCampaignRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCancelCampaignRequest := _CancelCampaignRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCancelCampaignRequest)

	if err != nil {
		return err
	}

	*o = CancelCampaignRequest(varCancelCampaignRequest)

	return err
}

type NullableCancelCampaignRequest struct {
	value *CancelCampaignRequest
	isSet bool
}

func (v NullableCancelCampaignRequest) Get() *CancelCampaignRequest {
	return v.value
}

func (v *NullableCancelCampaignRequest) Set(val *CancelCampaignRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelCampaignRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelCampaignRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelCampaignRequest(val *CancelCampaignRequest) *NullableCancelCampaignRequest {
	return &NullableCancelCampaignRequest{value: val, isSet: true}
}

func (v NullableCancelCampaignRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelCampaignRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
