FROM rust:latest

COPY pgdg.gpg /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg
COPY pgdg.list /etc/apt/sources.list.d/pgdg.list
COPY isc-kea-2-0.gpg /etc/apt/trusted.gpg.d/apt.isc-kea-2.0.gpg
COPY isc-kea-2-0.list /etc/apt/sources.list.d/isc-kea-2.0.list

RUN curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
RUN apt-get install -y curl postgresql-14 build-essential isc-kea-dhcp4-server isc-kea-dhcp6-server isc-kea-dev libboost-dev gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu libudev-dev libfreeipmi-dev libfreeipmi17 libipmiconsole-dev libipmiconsole2 libssl-dev clang automake cmake pkg-config sudo iproute2 && rm -rf /var/lib/apt/lists/*
RUN rustup component add rustfmt
RUN cargo install cargo-cache cargo-make mdbook mdbook-mermaid && cargo cache -r registry-index,registry-sources
RUN curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-amd64  && chmod +x ./kind && mv kind /usr/local/bin
RUN cd /usr/local/bin && curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x /usr/local/bin/kubectl
RUN /etc/init.d/postgresql start && su postgres -c "/usr/lib/postgresql/14/bin/createuser -d root" && /etc/init.d/postgresql stop
RUN cd /usr/local/bin && curl -fL https://getcli.jfrog.io | sh
RUN mkdir /usr/local/go && cd /usr/local/go && curl -Lo go.tar.gz https://go.dev/dl/go1.18.3.linux-amd64.tar.gz && tar --strip-components 1 -zxf go.tar.gz && rm -f go.tar.gz
ENV PATH "$PATH:/usr/local/go/bin"
