# SPDX-FileCopyrightText: Copyright (c) 2021-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

FROM alpine:latest

ENV HELM_VERSION=3.10.3
ENV HELM_URL=https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz

# kubectl (possibly in gcloud?)
ENV KUBECTL_VERSION=1.23.15
ENV KUBECTL_URL=https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl

# Install dependencies
RUN apk --no-cache add -U openssl curl tar gzip bash ca-certificates git go vault ruby nodejs yarn npm python3 py3-pip openssh \
  && mkdir -p /opt

# Install semver-tool
RUN curl -L -o /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver \
  && chmod +x /usr/local/bin/semver

# Install helm-docs
RUN wget -q -O - https://github.com/norwoodj/helm-docs/releases/download/v1.11.0/helm-docs_1.11.0_Linux_x86_64.tar.gz | tar -zxf - \
  && mv helm-docs /usr/local/bin \
  && chmod +x /usr/local/bin/helm-docs

RUN wget -q -O - https://github.com/mikefarah/yq/releases/download/v4.30.8/yq_linux_amd64.tar.gz | tar -zxf - \
  && mv yq_linux_amd64 /usr/local/bin/yq \
  && chmod +x /usr/local/bin/yq

RUN wget -q -O - https://github.com/zegl/kube-score/releases/download/v1.16.1/kube-score_1.16.1_linux_amd64.tar.gz | tar -zxf - \
  && mv kube-score /usr/local/bin \
  && chmod +x /usr/local/bin/kube-score

RUN wget -q -O - https://github.com/stackrox/kube-linter/releases/download/0.6.0/kube-linter-linux.tar.gz | tar -zxf - \
  && mv kube-linter /usr/local/bin/kube-linter \
  && chmod +x /usr/local/bin/kube-linter

# Install kubectl
RUN curl -L -o /usr/local/bin/kubectl ${KUBECTL_URL} \
  && chmod +x /usr/local/bin/kubectl \
  && kubectl version --client

# Install Helm
RUN wget -q -O - ${HELM_URL} | tar zxf - \
    && mv linux-amd64/helm /usr/bin/ \
    && chmod +x /usr/bin/helm \
    && helm version --client

# Install kubeval and cm-push
RUN mkdir -p $HELM_HOME/plugins && \
    helm plugin install https://github.com/instrumenta/helm-kubeval && \
    helm plugin install https://github.com/chartmuseum/helm-push

RUN gem install --no-document danger danger-prose danger-gitlab danger-yamlint gitlab bundler
RUN yarn global add alex@9 && yarn cache clean

RUN wget -q -O - https://github.com/errata-ai/vale/releases/download/v2.15.4/vale_2.15.4_Linux_64-bit.tar.gz | tar -zxf - \
  && mv vale /usr/local/bin \
  && chmod +x /usr/local/bin/vale

RUN pip3 install yamllint
RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh && \
  ssh-keyscan -p 12051 gitlab-master.nvidia.com  >> /root/.ssh/known_hosts
RUN printf "Host gitlab-master.nvidia.com\n\tPort 12051" > /root/.ssh/config
