# SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
FROM arm64v8/rust:1.71-slim-bookworm

# Change CACHEKEY to whatever so docker doesn't re-use the cache from before if you want apt to actually run.
#
# https://github.com/moby/moby/issues/1996
# https://github.com/moby/buildkit/issues/4294
#
RUN CACHEKEY=3283yu9283 apt update &&  \
	DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt upgrade -y && \ 
	DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y \
		automake \
		binutils-aarch64-linux-gnu \
		build-essential \
		clang \
		cmake \
		cpio \
		curl \
		dosfstools \
		fdisk \
		gcc-aarch64-linux-gnu \
		iproute2 \
		iputils-ping \
		jq \
		kea-dev \
		kea-dhcp4-server \
		libboost-dev \
		libgrpc-dev \
		libopenipmi-dev \
		libprotobuf-dev \
		libssh-dev \
		libssl-dev \
		libudev-dev \
		pkg-config \
		postgresql-15 \
		protobuf-compiler \
		sudo \
		unzip \
		wget \
		git \
	&& rm -rf /var/lib/apt/lists/*

RUN rustup component add rustfmt
RUN cargo install cargo-cache cargo-make mdbook mdbook-mermaid sccache && cargo cache -r registry-index,registry-sources

# install stuff that's not in debian
RUN curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
RUN curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-arm64  && chmod +x ./kind && mv kind /usr/local/bin
RUN cd /tmp && curl -Lo ./grpcurl.tar.gz https://github.com/fullstorydev/grpcurl/releases/download/v1.8.7/grpcurl_1.8.7_linux_arm64.tar.gz && tar xzf grpcurl.tar.gz && chmod +x ./grpcurl && mv grpcurl /usr/local/bin/ && rm LICENSE && rm grpcurl.tar.gz
RUN cd /tmp && curl -Lo vault.zip https://releases.hashicorp.com/vault/1.14.1/vault_1.14.1_linux_arm64.zip && unzip vault.zip && chmod u+x vault && mv vault /usr/local/bin/ && rm vault.zip
RUN cd /usr/local/bin && curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl" && chmod +x /usr/local/bin/kubectl

# create a postgres user
RUN /etc/init.d/postgresql start && su postgres -c "/usr/lib/postgresql/15/bin/createuser -d root" && /etc/init.d/postgresql stop
