# SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

# This should match rust-toolchain.toml
ARG CONTAINER_BUILD_X86_64
ARG CONTAINER_RUNTIME_X86_64

FROM $CONTAINER_BUILD_X86_64 as builder
ARG CI_COMMIT_SHORT_SHA
ENV CI_COMMIT_SHORT_SHA $CI_COMMIT_SHORT_SHA

ARG VERSION
ENV VERSION $VERSION
ENV CONTAINER_REPO_ROOT=/carbide

RUN USER=root cargo new --bin carbide
WORKDIR ./carbide
COPY . ./

RUN export CARGO_MAKE_SKIP_CODECOV="true" && \
  export DATABASE_URL="postgresql://%2Fvar%2Frun%2Fpostgresql" && \
  export SCCACHE_DIR=/sccache && \
  export RUST_WRAPPER=sccache && \
  /etc/init.d/postgresql start && \
  sudo -u postgres psql -c "ALTER USER root WITH SUPERUSER;" && \
  createdb root && \
  cargo make clippy-flow && \
  cargo make check-format-flow && \
  cargo make workspace-ci-flow

# After build, copy the release into the runtime container
FROM $CONTAINER_RUNTIME_X86_64
RUN mkdir -p /opt/carbide/migrations && \
    mkdir -p /opt/carbide/pxe/templates && \
    mkdir -p /opt/carbide/static

COPY --from=builder ["/carbide/target/release/carbide-api", "/carbide/target/release/carbide","/carbide/target/release/carbide-dns", "/carbide/target/release/forge-admin-cli", "/carbide/target/release/forge-dpu-agent", "/opt/carbide/"]
COPY --from=builder /carbide/target/release/libdhcp.so /usr/lib/x86_64-linux-gnu/kea/hooks

COPY api/migrations/ /opt/carbide/migrations/
COPY pxe/templates/*  /opt/carbide/pxe/templates/
COPY pxe/Rocket.toml /opt/carbide/
COPY pxe/artifacts.json /opt/carbide/
COPY api/casbin-policy.csv /opt/carbide/

ENV CASBIN_POLICY_FILE=/opt/carbide/casbin-policy.csv
