#
# Lightweight container for generic CI tasks
#
FROM bash:alpine3.20

RUN apk add --update --no-cache \
    curl \
    git \
    jq \
    unzip \
    wget

ENV VAULT_VERSION="1.16.1"
ENV VAULT_BINARY="vault_${VAULT_VERSION}_linux_amd64.zip"

RUN apk add --update --virtual .deps --no-cache gnupg && \
    cd /tmp && \
    wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/${VAULT_BINARY} && \
    wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS && \
    wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS.sig && \
    wget -qO- https://www.hashicorp.com/.well-known/pgp-key.txt | gpg --import && \
    gpg --verify vault_${VAULT_VERSION}_SHA256SUMS.sig vault_${VAULT_VERSION}_SHA256SUMS && \
    grep ${VAULT_BINARY} vault_${VAULT_VERSION}_SHA256SUMS | sha256sum -c && \
    unzip /tmp/${VAULT_BINARY} -d /usr/local/bin/ vault && \
    rm -f ${VAULT_BINARY} vault_${VAULT_VERSION}_SHA256SUMS vault_${VAULT_VERSION}_SHA256SUMS.sig && \
    apk del .deps
