FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install --assume-yes unzip libudev-dev:arm64 libssl-dev:arm64

RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip && \
    mkdir /protobuf && \
    unzip protoc-3.15.8-linux-x86_64.zip -d /protobuf && \
    chmod -R 755 /protobuf
ENV PATH="/protobuf/bin:${PATH}"
