FROM nvcr.io/nvidian/nvforge-devel/forge-admin-cli:latest

ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install -y \
    python3.11-full \
    wget \
    unzip

WORKDIR /tests
COPY ./tests/machine-lifecycle/requirements.txt machine-lifecycle/requirements.txt
RUN python3 -m venv venv
RUN venv/bin/pip install --no-cache-dir --upgrade -r machine-lifecycle/requirements.txt
