# SPDX-FileCopyrightText: Copyright (c) 2021-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
FROM arm64v8/ubuntu:focal

RUN apt update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y curl wget cpio build-essential libboost-dev gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu libudev-dev libssl-dev clang automake cmake pkg-config sudo iproute2 jq unzip && rm -rf /var/lib/apt/lists/*
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
RUN /root/.cargo/bin/rustup component add rustfmt
RUN /root/.cargo/bin/cargo install cargo-cache cargo-make mdbook mdbook-mermaid sccache && /root/.cargo/bin/cargo cache -r registry-index,registry-sources
RUN cd /usr/local/bin && curl -fL https://getcli.jfrog.io | sh
RUN mkdir -p /opt/protobuf && \
  rm -rf /tmp/protobuf && \
  mkdir -p /tmp/protobuf && \
  curl -L https://github.com/protocolbuffers/protobuf/releases/download/v21.5/protoc-21.5-linux-aarch_64.zip -o /tmp/protobuf/protobuf.zip && \
  unzip -d /tmp/protobuf /tmp/protobuf/protobuf.zip && \
  mv /tmp/protobuf/bin/protoc /opt/protobuf/ && \
  mv /tmp/protobuf/include /opt/protobuf/ && \
  rm -rf /tmp/protobuf
ENV PATH "$PATH:/opt/protobuf:/root/.cargo/bin"
ENV PROTOC "/opt/protobuf/protoc"
ENV PROTOC_INCLUDE "/opt/protobuf/include"
