FROM debian:trixie

RUN apt-get update && apt-get -y dist-upgrade && apt-get install -y --no-install-recommends \ 
pdns-backend-remote \
ca-certificates \
curl \
gnupg
RUN mv /etc/powerdns/pdns.conf /etc/powerdns/pdns.conf.orig

# DNS ports
EXPOSE 5353/udp
EXPOSE 5353/tcp

# webserver port
EXPOSE 8081/tcp

ENTRYPOINT ["/usr/sbin/pdns_server"]
