sequenceDiagram
    note left of BlueField ARM: Start EFI NetBoot
    participant BlueField ARM
    participant Cloud Init

    BlueField ARM->>Carbide: DHCP Discovery
    Carbide-->>Carbide: Allocate IP/Hostname
    Carbide-->>BlueField ARM: Boot discovery image

    loop discovery
        BlueField ARM->>BlueField ARM: Inventory hardware
        note right of BlueField ARM: Gather serial numbers, models, interface addresses, etc
        rect rgb(255, 163, 164)
        BlueField ARM->>BlueField BMC: Generate & Set BMC username
        BlueField ARM->>BlueField BMC: Gather BMC lan connectivity 
        end
    end
    BlueField ARM->>Carbide: Upload discovery + BMC info
    Carbide-->>BlueField ARM: Shutdown
    BlueField ARM->>Carbide: Netboot
    Carbide-->>BlueField ARM: Install BFB v.X

    loop Install
        BlueField ARM->>BlueField ARM: Provision BFB
        BlueField ARM->>Cloud Init: Customize Image
        Cloud Init->>Cloud Init: Setup local auth
        Cloud Init->>Cloud Init: Install container runtime
        Cloud Init->>Cloud Init: Configure static pods
        Cloud Init->>Cloud Init: Configure Bluefield Parameters
        Cloud Init-->>BlueField ARM: return success
    end
    BlueField ARM->>Carbide: Inform Install Completed
    Carbide->>BlueField ARM: Shutdown
    Carbide->>Carbide: Update State to reboot from Disk
    BlueField ARM->>Carbide: Netboot
    Carbide-->>BlueField ARM: Boot from Disk
