graph TB
  A(Hardware / Racks ordered)
  B(Hardware / Racks arrive)
  C(DC ops racks and cables hardware per elevation)
  D(DC ops powers on machines)
  E(Generate rack elevation)
  A --> B
  B --> C
  C --> D
  E --> C
  A --> E
  N0[Allocate IP subnets to racks]
  N1[Provision network fabric]
  N2[Populate Network in nvmetal]
  C --> N1
  N1 --> D  
  N0 --> N1
  N2 --> D
  N0 --> N2
  M0[Machine initiates DHCP]
  M1{nvmetal takes over}
  D --> M0
  M0 --> M1
  
