graph TD;
  new --> adopted;
  adopted --> tested;
  new --> broken;
  commissioned --> allocated;
  adopted --> broken;
  tested --> broken;
  commissioned --> broken;
  decommissioned --> tested;
  tested --> commissioned;
  decommissioned --> new;
  allocated --> broken;
  commissioned --> decommissioned;
  allocated --> decommissioned;
  broken --> decommissioned;
  broken --> tested;
